### ISSUE TITLE
wnmtl.org working in the morning, not working in the evening TypeError: Failed to fetch 

### ISSUE THREAD

**Issue by Davi101** [dteviot/WebToEpub#775] opened 2022-07-19 18:18 UTC
Yesterday there was an error [TypeError: Failed to fetch] reinstalled the extension several times, did not help.
 This morning everything worked, but by the evening it did not work again.
 Checked other novels now. smaller short stories can still be downloaded, but larger ones are not.

https://www.wnmtl.org/book/9034-quick-transmigration-cannon-fodder-s-record-of-counterattacks

**Comment by dteviot** [comment] 2022-07-19 20:03
@Davi101
Closing as duplicate of https://github.com/dteviot/WebToEpub/issues/772

**Closed by dteviot** 2022-07-19 20:03 UTC
Labels: Status: Duplicate
