### ISSUE TITLE
Remove useless link from metadata

### ISSUE THREAD

**Issue by budikesuma** [dteviot/WebToEpub#506] opened 2021-04-13 05:14 UTC
can you remove that useless link from the metadata?  it always appears and results in an error loading metadata.

Novel link:
https://www.wuxiaworld.com/novel/rise

![Screenshot_20210413-120652_Kiwi Browser](https://user-images.githubusercontent.com/50254552/114500201-1c6cb800-9c17-11eb-89e3-eb035afa5aa0.jpg)

**Comment by gamebeaker** [comment] 2021-04-13 06:59
@budikesuma thanks for this bug report i am going to look into it in the afternoon aprox. 8pm (UTC+2).

**Comment by gamebeaker** [comment] 2021-04-13 16:48
@budikesuma @dteviot 
i was able to reproduce your error in the morning as you postet but now it is ok the problem is that novelupdates have a latest Discussions board
![image](https://user-images.githubusercontent.com/9269847/114589471-fb907b00-9c87-11eb-9404-eccba91bc3e5.png)
and in this there was a thread with the name "rise" that is why it happend it is fixable if in 
main.js line 462 "[0]" without "" is added after .textContent==titelname) and before ;
and for wlnupdate to prevent such errors
main.js line 475 "[0]" without "" is added after .textContent==titelname) and before ;
i am not going to create a pull request for this short fix.

**Comment by dteviot** [comment] 2021-04-14 09:16
@gamebeaker 
Thanks, fix committed.  Also fixed a broken element at same time.

@budikesuma
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by dteviot** [comment] 2021-04-15 08:36
@budikesuma
Updated version (0.0.0.130) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.

**Closed by dteviot** 2021-04-15 08:36 UTC
Labels: Status: Completed
