### ISSUE TITLE
Please add site https://app.yoru.world

### ISSUE THREAD

**Issue by shonetypto** [dteviot/WebToEpub#1616] opened 2024-12-27 04:22 UTC
Hello, 

Sorry to bug but I found a new site that has me stumped. I'm a firefox user and I'm able to view inspector mode on app yoru world, find the appropriate selector for the body of text and copy it, however the extension cannot find the text. 

Here is the chapters page: https://app.yoru.world/en/story/273/chapters

I used the default Parser and have used the correct selector for the text, however I am still receiving this message: "Could not find content element for web page"

### What settings did you use?  What didn't work?
* URL of first chapter: https://app.yoru.world/en/story/273/read/5867
* CSS selector for element holding content to put into EPUB: .__className_d48d41
* CSS selector for element holding Title of Chapter: N/A
* CSS selector for element(s) to remove: N/A

I have no developer skills of note but I can try to create a new Parser following the instructions given. 

For now I've been going in chapter by chapter to copy the content in a new epub since I'm able to extract the content from the Inspector directly. (It's just taking me forever.) I'm honestly just curious to figure out what the issue is at this point. 

Thanks again for everything you do. <3

**Comment by ImLJS** [comment] 2024-12-27 06:31
@shonetypto duplicate of #1389 #1334

**Comment by shonetypto** [comment] 2024-12-28 00:01
> @shonetypto duplicate of #1389 #1334.
> 
> Due to the mentioned reason in 1334 -> we can not able to retrieve the content of the page.
> 
> Main issue being that the content of the chapter is being sent from aws cloud

Thank you! I'll try to figure something else out. :)

**Closed** 2024-12-30 04:43 UTC
Labels: Status: Duplicate

**Comment by ImLJS** [comment] 2024-12-30 13:08
@dteviot I attempted this, i am getting an HTML document in content. So, how to use the HTML document to get the content of the chapter 

Flow is like this :

1. Get Book ID from URL
2. Fetch JSON from this path - `https://pxp-main-531j.onrender.com/api/v1/books/${bookId}`
3. For each Chapter -> there is a rest url -> `https://pxp-main-531j.onrender.com/api/v1/book_chapters/${chapter.id}/content`
4. Use URL (3) to fetch JSON to get AWS Url
5. Use aws URL to fetch to get content in the form of HTML document

```
"use strict";

parserFactory.register("app.yoru.world", function () {return new YoruParser();});

class YoruParser extends Parser {
    constructor() {
        super();
    }

    async getChapterUrls(dom) {
        const bookId = dom.baseURI.split("/").pop();
        console.log("BookID", bookId);
        let restURL = `https://pxp-main-531j.onrender.com/api/v1/books/${bookId}`;
        let json = (await HttpClient.fetchJson(restURL)).json;
        console.log("JSON : ", json);
        let chapterUrls = [];
        json.chapters.forEach(async chapter => {
            const tempUrl = `https://pxp-main-531j.onrender.com/api/v1/book_chapters/${chapter.id}/content`;
            const awsURL = (await HttpClient.fetchJson(tempUrl)).json;
            const content = (await HttpClient.fetchHtml(awsURL)).responseXML;
            console.log("Content : ", content);            
            chapterUrls.push({
                sourceUrl: awsURL,
                title: chapter.title,
            });
        });
        return chapterUrls
    }

    async fetchChapter(url) {
        const doc = (await HttpClient.fetchHtml(url)).responseXML;
        console.log("DOC", doc);
        return doc;
    }

    findContent(dom) {
        return dom.querySelector("div[class^='__className']");
    }

    extractTitleImpl(dom) {
        return dom.querySelector("h1");
    }

    findChapterTitle(dom) {
        return dom.querySelector("div.text-2xl").textContent;
    }

    findCoverImageUrl(dom) {
        return util.getFirstImgSrc(dom, "div.hidden.flex-row");
    }

    getInformationEpubItemChildNodes(dom) {
        return [...dom.querySelectorAll("div[class^='showmore_content']")];
    }
}

```

**Comment by dteviot** [comment] 2024-12-30 20:27
@ImLJS 

I'm not sure why you're telling me this.  If it works, just make the commit.
