### ISSUE TITLE
Wnmtl.org not working again 

### ISSUE THREAD

**Issue by Tanzil-Ar-Rafee** [dteviot/WebToEpub#801] opened 2022-09-01 16:07 UTC
Wnmtl.org takes too long "Searching for URLs", then says "TypeError: Failed to fetch". Hope you can fix it soon. Cheers!

**Comment by dteviot** [comment] 2022-09-03 07:11
@Tanzil-Ar-Rafee 
I tried https://wnmtl.org/book/2124-tranxending-vision and there was no problem?
This sounds like a duplicate of https://github.com/dteviot/WebToEpub/issues/772
Did you run the test version, or the version from the Chrome or Firefox stores?

Please note, I have not yet updated the versions in the Chrome and Firefox stores.  (I've had RL issues.)

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by dteviot** [comment] 2022-09-10 22:52
@Tanzil-Ar-Rafee 
Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.

**Closed by dteviot** 2022-09-10 22:52 UTC
Labels: Status: In Progress
