### ISSUE TITLE
Manual CSS selectors: First chapter not included in chapter list

### ISSUE THREAD

**Issue by lll000111** [dteviot/WebToEpub#1125] opened 2023-11-28 20:57 UTC
**Describe the bug**
When manually entering URLs and CSS selectors for an unknown site, even though everything is correct and looks good, the first chapter - the one the dialog asked for as a starting point - is missing from the list of chapters.

**To Reproduce**

Site and novel: https://novellive.com/book/a-record-of-a-mortals-journey-to-immortality-immortal-realm

I get the Default parser and manually enter the relevant selectors as below:

- First chapter URL: https://novellive.com/book/a-record-of-a-mortals-journey-to-immortality-immortal-realm/chapter-1-fox-girl
- Chapter text: `div.txt`
- Title text: `span.chapter`
- Remove: `#pf-4012-1, #pf-3949-1, p:last-of-type`

![image](https://github.com/dteviot/WebToEpub/assets/25476357/4b8e2e87-2c93-4d19-98cd-c2342ccce2a3)

**Problem: After hitting "Apply" that first chapter is missing from the list of chapters!**

In addition, but that's another problem, I only get the chapters visible on the main page at that time - but the site uses 40-chapter paging.

![image](https://github.com/dteviot/WebToEpub/assets/25476357/db5cb8ed-6871-4b48-af3a-dccd7a1f839e)

**Expected behavior**
The starting chapter should be listed too.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome (latest)
 - Version 119.0.6045.160

**Comment by Kiradien** [comment] 2023-11-29 17:09
Not a fix for the main issue since I'm not too familiar with how the manual page is actually set up, but this may be of some help.

NovelLive seems to use the same format as FreeWebNovel.com - it's unlikely you'd be able to get the generic parser working for the site, but adding the following line to the top of FreeWebNovelParser should get it working. At least, if you're willing to edit js\parsers\FreeWebNovelParser.js and do a manual install. 

`parserFactory.register("novellive.com", () => new FreeWebNovelParser());`

I'll probably push that to my own branch as well if/when I get time, but it is a fix that _should_ theoretically work.

**Comment by dteviot** [comment] 2023-11-29 18:20
@Kiradien 

> I'll probably push that to my own branch as well if/when I get time, but it is a fix that should theoretically work.

I'll add it to my branch tonight and update the test build.  That should reduce a step for @lll000111
At same time I look into the missing page.

**Comment by lll000111** [comment] 2023-11-30 09:42
Just FYI for a workaround, I ended up using the "Edit Chapter URLs" button dialog. I added the first chapter, and I collected 40 URLs one at a time by manually paging and opening Web2Epub each time, getting the URLs from that same dialog. I added them all together in that dialog.
Acceptable effort, except that novel is going to have over 5000 chapters in the end so it will become more and more tedious :-)

**Comment by dteviot** [comment] 2023-11-30 18:13
@lll000111 
If you like to wait another 16 hours, I should get the paging done.  Had a thought this morning, might be easier than I first thought.

**Comment by dteviot** [comment] 2023-11-30 19:10
@lll000111 
Or you could go to freewebnovel (which WebToEpub does work for) and try there.
e.g. https://freewebnovel.com/a-record-of-a-mortals-journey-to-immortality-immortal-realm.html
Other sites: 
* https://innnovel.com/innnovel/a-record-of-a-mortals-journey-to-immortality-immortal-realm-296071
* https://bednovel.com/bednovel/a-record-of-a-mortals-journey-to-immortality-immortal-realm-59747

Incidentally, that title only lists as having 328 chapters.  where did you get 5000 from?

**Comment by dteviot** [comment] 2023-12-01 06:27
@lll000111 
I believe I've solved the mystery of the missing first chapter.

The answer is, it's not missing.  A link to the first chapter appears on the page with the button "Read first".  So, this link appears on the list of chapters with that title.  It's easier to see if you tick the "Show URLs of Chapters" button.  Screenshot:

![image](https://github.com/dteviot/WebToEpub/assets/5157081/d74c3a28-55c3-4790-a59f-5bec551581c9)

The reason that the title doesn't appear in the list of other chapters is because WebToEpub filters out duplicate URLs. 

As such, not a bug, nothing to fix.
For my notes: 15 minutes work.

**Comment by dteviot** [comment] 2023-12-01 06:37
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://novellive.com/book/a-record-of-a-mortals-journey-to-immortality-immortal-realm, chapter 1

For my notes: 50 minutes work (total)

**Comment by lll000111** [comment] 2023-12-01 08:55
> The reason that the title doesn't appear in the list of other chapters is because WebToEpub filters out duplicate URLs.

Wait - but "Read first" is not the title? Nothing to fix? I'm confused. Shouldn't the result be to have a chapter with the title "Fox girl"?

Thanks for all the effort!

**Comment by dteviot** [comment] 2023-12-01 20:00
@lll000111 

If you prefer, "Working as designed", or "Can't/Won't Fix"
The default parser doesn't know where the list of chapters is on a page, so shows all URLs (filtering for duplicates.)  The fact that the first occurrence of a link to the first chapter is outside the list of chapters and doesn't have the chapter's title is unfortunate, but site specific.

Trying to account for things like this in the default parser is an impossibly difficult task.
So, it makes a "best effort", and may require manual effort on the part of the user.

**Comment by dteviot** [comment] 2024-01-30 01:08
@lll000111 

Updated version (0.0.0.157) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.

**Closed by dteviot** 2024-01-30 01:08 UTC
Labels: Status: Completed
