### ISSUE TITLE
Suggestion / wild idea

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#48] opened 2016-07-12 05:57 UTC
Maybe you already had this idea, but I was thinking: what about getting some well formatted epubs, even hand made, and check them to see how they're actually formatted?
That could help with getting solutions/possibilities on how to build them.
Too wild?

**Comment by belldandu** [comment] 2016-07-12 19:09
The problem is less about building the epubs and more about filtering certain problems that appear on some pages within baka-tsuki that may cause issues with certain readers.

We already know the common formats for an epub in fact i was the one who suggested we adopt the more common format (with slight changes to prevent issues on some OS *cough*windows*cough*)

**Comment by dteviot** [comment] 2016-07-12 20:00
@typhoon71 
Not a bad suggestion.  The problem is finding what really are "well formatted epubs".
What would also be useful is a list of what changes you need to manually make to the epubs that WebToEpub generates?  Then I can look at automating that.  Similar to Belldandu's comment, what are the "oddball cases" we run into on Baka-Tsuki?

**Comment by toshiya44** [comment] 2016-07-12 21:28
I think the extension is doing pretty great. Just need to fix a few errors here and there and it will work almost perfectly with Baka-Tsuki. Not sure about other sites, since there haven't been any feedback from their users for a while...
As for formatting, I'd suggest adding a few more rules in the default stylesheet. (I can help with that if you decide to do that).

**Comment by dteviot** [comment] 2016-07-12 22:55
@toshiya44 
>  I'd suggest adding a few more rules in the default stylesheet. (I can help with that if you decide to do that).

Someone already sent me some suggestions.  However, I seem to have mislaid them.  If that was you, I apologise.  That said, sure, please post your recommendations.  Note: I don't promise to include them, but I will give them serious consideration.

**Comment by toshiya44** [comment] 2016-07-13 02:14
This is the general css I throw in for epubs made from BT pages. 
(Apparently I can't upload css files, so saved it as text)
[stylesheet.txt](https://github.com/dteviot/WebToEpub/files/360568/stylesheet.txt)

**Comment by dteviot** [comment] 2016-07-13 04:52
You can do it like this, I think.
```ccs
/*Style for svg images. I got this from BTE-Gen epunbs. Works nicely.*/
div.svg_outer {
  display: block;
  margin-bottom: 0;
  margin-left: 0;
  margin-right: 0;
  margin-top: 0;
  padding-bottom: 0;
  padding-left: 0;
  padding-right: 0;
  padding-top: 0;
  text-align: left;
}
div.svg_inner {
  display: block;
  text-align: center;
}

/*Centered headings and some margin to make sure it's not too close to the content.*/
h1, h2 {
  text-align: center;
  page-break-before: always;
  margin-bottom: 10%;
  margin-top: 10%;
}
h3, h4, h5, h6 {
  text-align: center;
  margin-bottom: 15%;
  margin-top: 10%;
}

/*Style for lists. Calibre sometimes has issues with the placement of lists, this fixes it.*/
ol, ul {
  padding-left: 8%;
}

/*In case there are images in img tags. It's up to you.*/
img {
  display: block;
  max-height: 100%;
  max-width: 100%;
  padding-bottom: 0;
  padding-left: 0;
  padding-right: 0;
  padding-top: 0;
  margin-left: auto;
  margin-right: auto;
  margin-bottom: 2%;
  margin-top: 2%;
}

/* To make hr tags more visible. BT doesn't use them very often but other sites might.*/
hr {
  color: black;
  background-color: black;
  height: 2px;
}

/*Styling all links.*/
a:link {
  text-decoration: none;
  color: #0B0080;
}
a:visited {
  text-decoration: none;
}
a:hover {
  text-decoration: underline;
}
a:active {
  text-decoration: underline;
}
```

**Comment by belldandu** [comment] 2016-07-13 05:26
Well there is one issue @dteviot when i tried to place everything in `OEBPS/Style/style.css` and then include that file everywhere i got some annoying complaints from epubcheck about src not being allowed as an attribute for style tags (not sure if this is still a problem or not since the dirty hack for doctype was implemented).

I will be looking into it tomorrow though.

**Comment by belldandu** [comment] 2016-07-13 06:09
epubcheck likes it now :D

**Comment by dteviot** [comment] 2016-07-19 10:20
@toshiya44
You've probably noticed, but in case you haven't, the default Stylesheet now uses the settings you've suggested.

**Comment by toshiya44** [comment] 2016-07-19 23:59
Yup, I noticed :D

**Comment by dteviot** [comment] 2016-07-31 05:21
I now run epubcheck against output to check for issues.
And stylesheet has been added.
So closing.

**Closed by dteviot** 2016-07-31 05:21 UTC
Labels: suggestion
