### ISSUE TITLE
Baka-Tsuki Multi-volume parser on series page.

### ISSUE THREAD

**Issue by belldandu** [dteviot/WebToEpub#95] opened 2016-12-17 08:23 UTC
Almost every series page on baka-tsuki has the same structure. With the "Full Text" links and all. Now if we could say parse these series pages to chase after volume links and do multi downloads then we could also get each volume's title as well as the author name and translator names automatically.

Atm is rather a slow going process to download one novel at a time especially if you setting a lot of stuff that's on the series page already but the parser can't see because its not on the volume page.

**Comment by belldandu** [comment] 2016-12-17 08:25
Should also be some sort of way to choose which novels to download (in case we get issues like #94)

**Comment by dteviot** [comment] 2017-11-13 19:24
Closing. This is mostly a duplicate of https://github.com/dteviot/WebToEpub/issues/98

**Closed by dteviot** 2017-11-13 19:24 UTC
Labels: Priority: Low, Status: Accepted, Type: Enhancement, Type: Suggestion
