### ISSUE TITLE
Please add site https://reaperscans.com

### ISSUE THREAD

**Issue by Jokakun** [dteviot/WebToEpub#1480] opened 2024-09-10 11:24 UTC
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://reaperscans.com/series/the-legendary-hero-is-an-academy-honors-student

### Note: I've tried the developer mode version of the app and it doesn't work.
![image](https://github.com/user-attachments/assets/12a4666d-00cf-4484-9f4b-77224c330a83)

**Comment by gamebeaker** [comment] 2024-09-10 11:26
Duplicate of: #1403 and #1064

**Closed by gamebeaker** 2024-09-10 11:26 UTC
Labels: Status: Duplicate
