### ISSUE TITLE
br tags

### ISSUE THREAD

**Issue by toshiya44** [dteviot/WebToEpub#34] opened 2016-06-30 08:34 UTC
In BakaTsukiParser.js it says,
`// discard br tags as epubcheck says they are invalid in the places they are at in xhtml
    util.removeElements(util.getElements(element, "br"));`

br tags are not invalid, they only need to be closed properly in xhtml, like `<br/>`
In Baka-Tsuki pages br tags show up as `<br>`, that's why epubcheck didn't like it.
Can you please replace all  `<br>` by `<br/>` instead of removing it?

**Comment by belldandu** [comment] 2016-06-30 15:19
Your asking me to basically go ahead and do a regex on html (which is not smart) even though epubcheck returns errors for <br>, <br/> and  <br /> because of there placement within the pages.

Because baka-tsuki and any other site can put br tags anywhere they please (which doesn't conform to the xhtml standard as certain places you just aren't supposed to put a br tag) they are removed.

**Comment by belldandu** [comment] 2016-06-30 16:58
Welp 
```
// Replace elements that are invalid in xhtml with their valid counter parts
BakaTsukiParser.prototype.replaceInvalidElements = function(element) {
    // replace br tags
    let brs = util.getElements(element, "br");
    for(let br of brs) {
        let newBr = document.createElement("br");
        br.parentNode.replaceChild(newBr, br);
    }
}
```
@dteviot i believe a doctype tag is in order.
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" 
   "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

**Comment by belldandu** [comment] 2016-06-30 18:39
Although doing this means we will have to import nodes before appending them

**Comment by dteviot** [comment] 2016-06-30 19:47
@belldandu & @toshiya44

My understanding is that the only problem this is giving at the moment is
epubcheck is reporting this as a violation.  Readers are not having a
problem with it.
As such, I'm regarding it as a "trivial" problem and I'm ignoring it until
more critical issues are fixed. See:  my most recent post to
https://baka-tsuki.org/forums/viewtopic.php?f=84&t=16114&start=45#p271810

If my understanding is incorrect, please let me know.

**Comment by belldandu** [comment] 2016-06-30 20:07
@dteviot well actually i already figured out a way to fix the br tags without breaking dom minipulation (its a bit hacky like the xml declaration thing)

Main problem for what i was doing (removing them) is that it completely removed some line breaks that where needed in some places.

Now what i do is i replace the br with the proper tag and then append a docType that accepts this br tag to the xhtml immediatly after the xml declaration.

This way it doesn't affect our dom manipulation and epub readers / epubcheck wont go nuts about the tag not being allowed where its at.

I will push the pull request in a bit.

**Comment by dteviot** [comment] 2016-06-30 20:36
I thought I was already adding that doc type tag.  But maybe I was doing it
at end, just before writing to the epub zip.
In which case, need to do it when create initial xhtml file to fill in
util.  Then chrome should automatically close the tag.

**Comment by belldandu** [comment] 2016-06-30 20:40
You create a document however non of the xhtml files have an actual doctype. There are a couple of other things that go along with this. Almost done with PR with push in 5 minutes @dteviot

**Comment by belldandu** [comment] 2016-06-30 20:50
@dteviot @toshiya44  see #35

**Comment by dteviot** [comment] 2016-07-02 22:31
@belldandu
BakaTsukiParser.replaceInvalidElements() which is supposed to close &lt;br&gt; tags does not appear to do anything useful.

See this test
``` javascript
test("replaceInvalidElements", function (assert) {
    let dom = new DOMParser().parseFromString(
        "<html>" +
            "<head><title></title></head>" +
            "<body>" +
                "<p>SomeText</p>" +
                "<br>" +
                "<p>More</p>" +
            "</body>" +
        "</html>",
        "text/html");
    let parser = new BakaTsukiParser();
    let content = dom.body.cloneNode(true);
    parser.replaceInvalidElements(content);

    // this assert fails.
    assert.equal(content.innerHTML, "<p>SomeText</p><br /><p>More</p>");
});

```

I think Chrome automatically closes the &lt;br&gt; tag when converting nodes from html to xhtml

See this test
``` javascript
test("replaceInvalidElements", function (assert) {
    let dom = new DOMParser().parseFromString(
        "<html>" +
            "<head><title></title></head>" +
            "<body>" +
                "<p>SomeText</p>" +
                "<br>" +
                "<p>More</p>" +
            "</body>" +
        "</html>",
        "text/html");
    let parser = new BakaTsukiParser();
    let content = dom.body.cloneNode(true);

    let xhtml = util.createEmptyXhtmlDoc();
    let body = xhtml.getElementsByTagName("body")[0];
    body.parentNode.replaceChild(content, body);

    assert.equal(xhtml.getElementsByTagName("body")[0].outerHTML, 
        "<body xmlns=\"http://www.w3.org/1999/xhtml\"><p>SomeText</p><br /><p>More</p></body>");
});
```

I also checked a Baka-Tsuki story with &lt;br&gt; tags and confirmed they are being closed in the generator's output when replaceInvalidElements() has been removed.
I think we need to look more carefully at what epubcheck is complaining about.  Possibly all that's needed is the doctype element.

**Comment by belldandu** [comment] 2016-07-03 01:45
@dteviot weird and ok.

**Comment by belldandu** [comment] 2016-07-12 19:38
@dteviot @toshiya44 can this be closed?

**Comment by dteviot** [comment] 2016-07-12 19:52
@belldandu  @toshiya44 
>can this be closed?

Only if epubcheck is now happy with the &lt;br /&gt; tags we're now using.  If not, that needs to be fixed.
Note, at current time I have not set up epubcheck to run on my system.

**Comment by belldandu** [comment] 2016-07-13 05:43
@dteviot will check tommorow

**Comment by belldandu** [comment] 2016-07-13 06:09
@dteviot 
```
[kami@Index ~]$ epubcheck Toaru_Maju...dexVolume1.epub 
Validating using EPUB version 2.0.1 rules.
ERROR(RSC-005): Toaru_Maju...dexVolume1.epub/OEBPS/Text/0006_Part_5.xhtml(66,7): Error while parsing file 'element "br" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")'.
ERROR(RSC-005): Toaru_Maju...dexVolume1.epub/OEBPS/Text/0006_Part_5.xhtml(66,115): Error while parsing file 'element "br" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")'.
ERROR(RSC-005): Toaru_Maju...dexVolume1.epub/OEBPS/Text/0008_Part_7.xhtml(13,7): Error while parsing file 'element "br" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")'.
ERROR(RSC-005): Toaru_Maju...dexVolume1.epub/OEBPS/Text/0008_Part_7.xhtml(13,115): Error while parsing file 'element "br" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")'.
ERROR(RSC-005): Toaru_Maju...dexVolume1.epub/OEBPS/Text/0008_Part_7.xhtml(72,7): Error while parsing file 'element "br" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")'.
ERROR(RSC-005): Toaru_Maju...dexVolume1.epub/OEBPS/Text/0008_Part_7.xhtml(72,115): Error while parsing file 'element "br" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")'.
ERROR(RSC-005): Toaru_Maju...dexVolume1.epub/OEBPS/Text/0009_Chapter_2_...e_7th-Egde.xhtml(59,7): Error while parsing file 'element "br" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")'.
ERROR(RSC-005): Toaru_Maju...dexVolume1.epub/OEBPS/Text/0009_Chapter_2_...e_7th-Egde.xhtml(59,115): Error while parsing file 'element "br" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")'.
ERROR(RSC-005): Toaru_Maju...dexVolume1.epub/OEBPS/Text/0009_Chapter_2_...e_7th-Egde.xhtml(134,7): Error while parsing file 'element "br" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")'.
ERROR(RSC-005): Toaru_Maju...dexVolume1.epub/OEBPS/Text/0009_Chapter_2_...e_7th-Egde.xhtml(134,115): Error while parsing file 'element "br" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")'.
ERROR(RSC-005): Toaru_Maju...dexVolume1.epub/OEBPS/Text/0010_Part_2.xhtml(173,7): Error while parsing file 'element "br" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")'.
ERROR(RSC-005): Toaru_Maju...dexVolume1.epub/OEBPS/Text/0010_Part_2.xhtml(173,115): Error while parsing file 'element "br" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")'.
ERROR(RSC-005): Toaru_Maju...dexVolume1.epub/OEBPS/Text/0018_Epilogue_T...ohibitorum.xhtml(35,7): Error while parsing file 'element "br" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")'.
ERROR(RSC-005): Toaru_Maju...dexVolume1.epub/OEBPS/Text/0018_Epilogue_T...ohibitorum.xhtml(35,115): Error while parsing file 'element "br" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")'.
ERROR(RSC-005): Toaru_Maju...dexVolume1.epub/OEBPS/Text/0018_Epilogue_T...ohibitorum.xhtml(108,7): Error while parsing file 'element "br" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")'.
ERROR(RSC-005): Toaru_Maju...dexVolume1.epub/OEBPS/Text/0018_Epilogue_T...ohibitorum.xhtml(108,115): Error while parsing file 'element "br" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")'.
ERROR(RSC-005): Toaru_Maju...dexVolume1.epub/OEBPS/Text/0018_Epilogue_T...ohibitorum.xhtml(112,7): Error while parsing file 'element "br" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")'.
ERROR(RSC-005): Toaru_Maju...dexVolume1.epub/OEBPS/Text/0018_Epilogue_T...ohibitorum.xhtml(112,115): Error while parsing file 'element "br" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")'.

Check finished with errors

epubcheck completed
```

Welp

**Comment by dteviot** [comment] 2016-07-13 22:04
Was extension running under Chrome or Firefox?  As noted in https://github.com/dteviot/WebToEpub/issues/49 I suspect Chrome closes &lt;br&gt; elements for us, but Firefox does not.

**Comment by belldandu** [comment] 2016-07-13 22:08
It was run under chromium @dteviot

**Comment by dteviot** [comment] 2016-07-14 00:42
@belldandu
Can you send me some of the offending files?  e.g. 0006_Part_5.xhtml and 0008_Part_7.xhtml, I'd like to take a closer look at exactly where/what the problem is.

**Comment by belldandu** [comment] 2016-07-14 01:16
I know exactly what the problem is. XD the change i made before where i just replaced the BR tags had actually fixed that issue. @dteviot

**Comment by dteviot** [comment] 2016-07-14 03:46
I want to confirm the problem that epubcheck is reporting is &lt:br&gt; elements that are not closed.  And not something else.
I've seen Chrome closing the tags, but if Chromium is not closing them, then it's possible that Chrome doesn't either, at least in some cases.
Deleting and re-creating the elements may result in closed tags, if it's creating XTHML elements, not HTML elements.  
I suspect the correct way to solve the problem is using importNode()  https://developer.mozilla.org/en-US/docs/Web/API/Document/importNode when we copy the "content" from the Baka-Tsuki HTML to the EPUB's XHTML.  example: http://stackoverflow.com/questions/12092532/how-to-convert-html-to-valid-xhtml.  Note, I also need to create the empty XHTML document correctly, using createElementNS(), and it's family.

Note, I have not yet tested this to confirm.  At moment, it's just a working hypothesis.

**Comment by toshiya44** [comment] 2016-07-18 00:10
I believe this issue is now fixed too. The plugin in sonako branch closes `br` tags properly.

**Comment by dteviot** [comment] 2016-07-18 08:53
I believe I now understand where the &lt;br&gt; error is coming from.
epubcheck wants the &lt;br&gt; enclosed in a &lt;p&gt; tag.
e.g. This XHTML fragment 
```xhtml
<body>
    <p>Some Text</p>
    <br />
    <p>More Text</p>
</body>
```
gives the error message 
> Error while parsing file 'element "br" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")'.

This XHTML fragment does not
```xhtml
<body>
    <p>Some Text</p>
    <p><br /></p>
    <p>More Text</p>
</body>
```

I've logged the issue with epubcheck https://github.com/IDPF/epubcheck/issues/700, and I'll see what they come back with.  Note, they have had a similar issue in the past. https://github.com/IDPF/epubcheck/issues/209

**Comment by dteviot** [comment] 2016-07-18 20:35
@toshiya44, @belldandu
Well, I got a response from the IDPF team

> If you're creating an EPUB 2, then that's correct. The br element isn't allowed as a child of the body in XHTML 1.1.
It's not an error in HTML5, and I can't reproduce in a conforming EPUB 3 publication.

I'm going to class this as a "won't fix".
The behaviour is technically wrong, but: 
1. The &lt;br /&gt; tags ARE closed, 
2. The vast majority of epub viewers handle it without a problem.
3. The effort required to determine if each &lt;br /&gt; tag is a child of the body or not is probably not worth it.  There are more useful things I can do with my time.

**Closed by dteviot** 2016-07-18 20:35 UTC
Labels: bug, low priority, wontfix

**Comment by belldandu** [comment] 2016-07-20 01:19
@dteviot Agreed.

If i have time when i get back in 6 months and all the other issues have been fixed i might take a crack at it.
But for now i agree with the "wontfix".
