### ISSUE TITLE
Please add site https://pagestage.kakao.com/novels/15543161

### ISSUE THREAD

**Issue by SaraDalbah** [dteviot/WebToEpub#822] opened 2022-09-25 10:15 UTC
Please add site https://pagestage.kakao.com/novels/15543161

**Comment by dteviot** [comment] 2022-10-01 03:27
@SaraDalbah 
This is a duplicate of https://github.com/dteviot/WebToEpub/issues/821
Site has changed layout, and unfortunately
1. I didn't write the parser for that site, and
2. It's in Korean (which I don't read) and it uses javascript calls to fetch content (so is difficult.)

**Comment by dteviot** [comment] 2022-10-10 03:05
@SaraDalbah 
Fix was provided by courli79, See: https://github.com/dteviot/WebToEpub/issues/827

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by dteviot** [comment] 2023-01-03 21:25
@SaraDalbah 

Updated version (0.0.0.151) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Closed by dteviot** 2023-01-03 21:25 UTC
Labels: Status: Duplicate, Status: Completed
