### ISSUE TITLE
[Enhancement] add chapter links manually, selectable chapters intervals, automatic table of content

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#73] opened 2016-09-12 18:53 UTC
**1. Add chapter links manually**
This idea comes from GravityTales and skythewood.blogspot.it.
I noticed the TOC with all the chapters of a LN/WN is actually missing the link for the most recent ones (Crazy Litch 59/60, Altina v8 ch2).
I was wondering if in cases like this it would be possible to "Add" some chapter links "manually" to the list... 
I suppose adding some at the end of the list would be enougn, since adding in the middle would mean that the TOC itself is broken (and I think it'll be harder to implement too).

**2. Selectable chapters intervals**
This idea comes from shikkakutranslations.org.
Since both of the novels translated on this site appear in the chapter list, it takes a lot to remove the unwanted ones (100+).
Would it be possible to implement something like intervals of chapters to select/unselect?

**3. Automatic table of content**
It would be nice to have something that adds an optional page with a table of content with links to the chapter pages.

**Comment by dteviot** [comment] 2016-09-12 19:19
@typhoon71 
> I was wondering if in cases like this it would be possible to "Add" some chapter links "manually" to the list.

I've been considering something like that myself.
More specifically, the need for a "generic parser" that shows all links and allows you to add/remove/reorder links as required.  The more difficult part is the generic "find the content from the text."  Some problem cases I run into are:
- http://skythewood.blogspot.co.nz/p/the-different-world-magic-is-too-behind.html.  If you look at this, you will see that the each of the first 3 links is to a different site with a different layout.
- https://wcctranslation.wordpress.com/table-of-contents/ some of the links are to "chapters" that are just links to the real chapter, or even links to links to the real chapter.

**Comment by typhoon71** [comment] 2016-09-14 20:22
Updated with point 2.

**Comment by dteviot** [comment] 2016-09-18 05:23
@typhoon71
Committed update to ExperimentalTabMode branch.
Click on "Edit Chapter URLs" to manually add/remove/edit the URLs.
Please let me know how it goes.

**Comment by typhoon71** [comment] 2016-09-18 09:59
Nice. I tested with shikkakutranslations.org, it makes editing a breeze.
I noticed that it's better to edit the links outside the addon window, for example with notepad++, because the tab with the links slows down (well, 400+ links...).

I think the button "Edit chapters url" that you see while in "edit mode" would be better if named "Apply changes" instead.

I added a 3rd request, it kind of popped in my mind while editing (automatic table of content).

**Comment by dteviot** [comment] 2016-09-18 19:17
@typhoon71
> I noticed that giving an invalid link throws an error telling you the (first) link that was wrong.
This happens on Gravity Tales with crazy lich too, where for some reason there are links for chapters not yet available (>65). An invalid link in the middle of a list will stop the fetching there.

That's not a bug, it's a feature.  Seriously, the intent is if there's a problem you'll know about it and are expected to fix it before carrying on.  If this is not satisfactory, please tell me what the behaviour should be.

> 3. Automatic table of content
It would be nice to have something that adds an optional page with a table of content with links to the chapter pages.

I'm confused.  How does this differ from the existing table of content that is generated?

**Comment by dteviot** [comment] 2016-09-19 08:26
@typhoon71 
> I think the button "Edit chapters url" that you see while in "edit mode" would be better if named "Apply changes" instead.

Done.

**Comment by dteviot** [comment] 2016-09-19 19:53
@typhoon71 
> For epubs there's no need for another TOC, it would be a duplicate, it was more for pdf printing, since the TOC is not visible when printing to pdf, and obv there's no links to be clicked.

The Calibre docs say it can generate a ToC for a PDF from the EPUB's ToC.  
https://manual.calibre-ebook.com/conversion.html#id16
And as this is an EPUB, not a PDF generator,  I see no need to do this.

I'm going to call this issue closed.  If you disagree, please feel free to add a comment.

**Closed by dteviot** 2016-09-19 19:53 UTC

**Comment by typhoon71** [comment] 2016-09-20 06:04
It's OK, I'm fine with this; actually, I'm quite happy with how this addon is progressing. :)
