### ISSUE TITLE
Tab Mode broken in firefox aurora and chromium 52 when hosted on a server

### ISSUE THREAD

**Issue by belldandu** [dteviot/WebToEpub#59] opened 2016-07-18 21:02 UTC
I get the starting URL option however i get no load and analyze button at all.

The test page is at https://ilp.moe/webtoepub/popup.html

**Comment by belldandu** [comment] 2016-07-18 21:09
![chrome](http://i.imgur.com/bud0UCV.png)
![firefox](http://i.imgur.com/6VCGY5M.png)

**Comment by dteviot** [comment] 2016-07-18 21:57
@belldandu 
Should be fixed when I implement https://github.com/dteviot/WebToEpub/issues/23#issuecomment-233252911

**Comment by dteviot** [comment] 2016-07-18 21:59
The problem is, the "Load and Analyse" button is only enabled when the call to get URL fails.
However, when running from a web page, the call to get URL isn't even legal javascript (wrong namespace) so it doesn't even get that far.

Need to figure out if running in popup mode, tab mode, or from web page.  I think that can be done by looking at the pages "base" value.

**Comment by dteviot** [comment] 2016-07-19 10:19
@belldandu 
Should be fixed in https://github.com/dteviot/WebToEpub/tree/AdvancedOptions if you want to give it a try.

**Comment by belldandu** [comment] 2016-07-20 01:25
CORS pls
![CORS](http://i.imgur.com/EYzsCxe.png)
There's no easy way to work around that.

**Comment by belldandu** [comment] 2016-07-20 02:00
One way to do this would be to have a library in nodejs that feeds the html to webtoepub
Of course for security reasons we would restrict said library to urls specified in the parser.

Sort of a side project i guess.

**Comment by dteviot** [comment] 2016-07-20 04:42
@belldandu
The simplest fix would be to get WebToEpub hosted on Baka-Tsuki.
Of course, then it would only work for Baka-Tsuki.

Another possibility:
Run it as a local file.  That's what I did last night.  Unzip the plug-in and load popup.html into browser.  That opens it in "Tab" mode and it worked for me.  At least, against RoyalRoad.

**Comment by dteviot** [comment] 2016-07-20 04:46
Hmmm.  Just tried the "local file" mode.
Doesn't work for Baka-Tsuki.

**Comment by belldandu** [comment] 2016-07-20 07:48
Of course it doesn't @dteviot For security reasons in javascript one domain/protocol/port cannot READ from another domain/protocol/port because of the SOP or Same Origin Policy.

Said domains CAN however WRITE to another domain/protocol/port (which i find HIGHLY REDUNDANT).

I also found out that script tags DO NOT follow the SOP (which is retarded and a HUGE flaw)

As for Hosting it on Baka-tsuki that still doesn't solve the OTHER issues for the other sites like the wayback machine ETC.

**Comment by dteviot** [comment] 2016-08-11 01:50
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest  suggests that setting XMLHttpRequest.mozSystem to true will bypass CORS.

**Comment by belldandu** [comment] 2016-09-30 18:35
But that's read only?
Would require everyone who visits the page to have that done in their own browser.

**Comment by dteviot** [comment] 2016-09-30 20:38
D'oh! You're correct.

**Comment by belldandu** [comment] 2016-10-02 05:05
Our best option here would be to either run a nodejs or php proxy to the site and pass it to the plugin. The problem is that by doing so we have to make the plugin amd proxy have security measures in place so it doesn't get abused by third parties. Either that or we ask every domain we add to the plugin to add CORS headers to allow us to make requests. (Pretty sure a few sites wont do that)

**Comment by belldandu** [comment] 2016-10-29 22:32
Firefox on mobile doesn't look like its caught up yet

![whale then](http://i.imgur.com/FRIetpG.png)

**Comment by belldandu** [comment] 2016-10-29 22:45
err @dteviot its doing the same thing on firefox aurora for android

**Comment by dteviot** [comment] 2016-11-02 03:55
@belldandu

Thanks, I haven't actually tested Firefox for Android.  Based on not getting any complaints, I'm guessing no one is using it.  (There's only about 250 downloads of the FireFox version, vs. 3800 versions in use on Chrome last I looked.)

**Comment by Quaturn** [comment] 2016-11-02 11:11
Well I can not speak for the others but me I am using firefox version of the addon but I downloaded it only once from official web page. Since then I am updating it from here by copying the latest dev version.

**Comment by belldandu** [comment] 2016-11-03 08:13
Potential replacement for server mode. #81

**Comment by dteviot** [comment] 2017-12-10 19:26
Closing latest version of extension is working on  Firefox for Android version 57.0.1.

**Closed by dteviot** 2017-12-10 19:26 UTC
Labels: Priority: Low, Status: On Hold, Type: Bug
