### ISSUE TITLE
Downloads saving as Zip rather than EPUB

### ISSUE THREAD

**Issue by patcan3609** [dteviot/WebToEpub#297] opened 2019-10-27 05:25 UTC
My files are downloaded as Zip files rather than EPUB files and there arent any options of changing to an EPUB file during the saving process. The Zip file contains the content in separate chapters that links the chapter to its webpage.

**Comment by dteviot** [comment] 2019-10-27 21:58
@patcan3609 
This sounds like a duplicate of https://github.com/dteviot/WebToEpub/issues/191
Please read through **_all_** of it, as there are a number of things that can cause this problem.
However, the short form is:
1. Most likely cause is conflict with some other extension you have loaded.
2. After WebToEpub creates the *.zip file, rename the file with a .epub extension and it will work fine as an epub file.  (FYI.  epub files are a special kind of zip file.)

**Comment by patcan3609** [comment] 2019-10-28 01:21
> @patcan3609
> This sounds like a duplicate of #191
> Please read through **_all_** of it, as there are a number of things that can cause this problem.
> However, the short form is:
> 
> 1. Most likely cause is conflict with some other extension you have loaded.
> 2. After WebToEpub creates the *.zip file, rename the file with a .epub extension and it will work fine as an epub file.  (FYI.  epub files are a special kind of zip file.)

Theres no .zip in the file name. Its directly downloaded into a compressed zip file.

**Comment by dteviot** [comment] 2019-10-28 07:05
@patcan3609
> There's no .zip in the file name. Its directly downloaded into a compressed zip file.

The compressed zip file **is** an EPUB file.
I think it's still basically the same problem I told you before.  WebToEpub is creating an EPUB file, but you've got an extension that's messing up the name of the file.
The file from WebToEpub is fine, it's just the name that's messed up.  Rename it to something ending with .epub and it should work.

That said, I am curious what name is it giving the files?

**Comment by patcan3609** [comment] 2019-10-28 07:30
> @patcan3609
> 
> > There's no .zip in the file name. Its directly downloaded into a compressed zip file.
> 
> The compressed zip file **is** an EPUB file.
> I think it's still basically the same problem I told you before. WebToEpub is creating an EPUB file, but you've got an extension that's messing up the name of the file.
> The file from WebToEpub is fine, it's just the name that's messed up. Rename it to something ending with .epub and it should work.
> 
> That said, I am curious what name is it giving the files?

I only have adblock extension activated. The compressed zip file has a lot of different files inside in the form of xhtml document. The name of the file is just the novel name.

**Comment by patcan3609** [comment] 2019-10-28 07:31
[Yang_Xia...ouse_Dad.epub.zip](https://github.com/dteviot/WebToEpub/files/3777557/Yang_Xia.ouse_Dad.epub.zip)

**Comment by dteviot** [comment] 2019-10-28 10:18
That file is definitely an epub file.
You just need to remove the ".zip" from the end, and most epub readers will accept it.
e.g. change name from
> Yang_Xia.ouse_Dad.epub.zip

to
> Yang_Xia.ouse_Dad.epub

> The compressed zip file has a lot of different files inside in the form of xhtml document. 

That's what an epub file is like. It's a zip file containing XML and XHTML documents. See: https://en.wikipedia.org/wiki/EPUB

> I only have adblock extension activated. 

If you read https://github.com/dteviot/WebToEpub/issues/191 you should see that there are a number of other ways the file getting a .zip extension might occur.  As I don't have access to your PC, I can't say which one it is.

**Comment by patcan3609** [comment] 2019-10-28 16:38
Thanks, I managed to change it to epub. By any chance do you know if Winrar is the source of the problem?

**Comment by dteviot** [comment] 2019-10-29 04:18
@patcan3609
> By any chance do you know if Winrar is the source of the problem?

Sorry, I don't know.  
I don't use it.  
You could uninstall Winrar, try using WebToEpub and see what happens, then put Winrar back.

**Comment by dteviot** [comment] 2019-10-30 18:43
@patcan3609
Well, this is embarrassing.  It's now doing it to me as well.
It looks like there's been a change to Chrome, I think it's now looking at the file to be saved, seeing it looks like a zip file and offering to save it as a zip.
When the "Save As" dialog appears, Check the "Save as type" drop down at the very bottom of the dialog.  It it set to "Compressed (zipped) folder (*.zip)", and does the filename to save as end with ".zip"?

To save as an epub, I think you need to change the filename to end in ".epub", and set the drop down to "All Files (*.*)"
Please confirm the above for me, and I'll see what I need to do to tell Chrome it's not an epub.  Thanks

**Comment by patcan3609** [comment] 2019-10-31 08:25
Changing the ending of the file name to .epub does indeed save into an EPUB file while setting the drop down to "All Files". I still dont see the "save as type" option for EPUB files though.

**Comment by dteviot** [comment] 2019-10-31 18:33
@patcan3609 
> I still don't see the "save as type" option for EPUB files though.

Can you confirm that the "save as type" is set to zip when the Save as dialog opens?

It it is doing that, then I'm hoping that's because your copy of WebToEpub hasn't updated itself yet.  (You could check by opening the extensions management tab in chrome (See:  section "Manage your extensions" on https://support.google.com/chrome_webstore/answer/2664769?hl=en) and check the version.

Or just wait and see if it starts behaving in a day or two.

That said, I think you've at least got a solution to the "save as zip" problem.  Even if it does require a bit more work when the Save as dialog opens.

**Comment by patcan3609** [comment] 2019-11-04 09:03
Ok the new version seems to work now for downloading EPUB files. Thanks for your help!

**Closed** 2019-11-04 18:03 UTC
