### ISSUE TITLE
BakaTsuki - Empty page after Image gallery

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#28] opened 2016-06-28 11:26 UTC
In calibre, after the images at the start of a epub, there's a white page, just before the novel start.
Can you check if it's caused by the reader or not? It's not supposed to be there.
I can't try with sumatra because there's the link issue still around (so the page isn't empty and I don't know if it's on calibre side).

**Comment by belldandu** [comment] 2016-06-28 12:09
Caused by #24

**Comment by belldandu** [comment] 2016-06-28 13:39
Well As it turns out the novel illustrations bit is treated as all 1 page. So in the case of this being like a real book / LN (one that has a blank page between copyright / other junk and the story). This is a Wontfix now. As there is no real way to fix this anyway (trust me i tried). @dteviot

**Comment by belldandu** [comment] 2016-06-28 13:47
@dteviot we could fill in this page with something by placing some elements after all the images however doing anything other than that is not recommended at this point.

**Comment by belldandu** [comment] 2016-06-28 20:34
See #31

**Comment by typhoon71** [comment] 2016-06-28 20:58
I just noticed that something similar can happen at the start of the gallery.
Check: https://www.baka-tsuki.org/project/index.php?title=Clash_of_Hexennacht:Volume1.
I think those spurious /div should be cleaned out.
I'm trying to see what happens editing manually the xhtml.
Maybe a postprocessor of sort could be an idea?

**Comment by belldandu** [comment] 2016-06-28 21:25
I got rid of the spurious divs already. see #30

**Comment by typhoon71** [comment] 2016-06-29 05:36
Is it already avail/merged in sonako?

**Comment by dteviot** [comment] 2016-06-29 07:30
@typhoon71 
Yes.  You can see what's been done at https://github.com/dteviot/WebToEpub/commits/sonako

All going well, I should be submitting to Google within 30 minutes.

**Comment by typhoon71** [comment] 2016-06-29 07:43
Thanks; I'll bookmark that (so I don't have t ask every time).

**Comment by belldandu** [comment] 2016-07-03 01:58
Classified as a bug for now.

**Comment by dteviot** [comment] 2016-07-10 19:47
@belldandu 

I'm suspecting the problem is that there is some white space tags (either <p> or <br>) after the images. but before the end of the generated XHTML file. As the image takes an entire page, the reader puts the white space on another page.  Then it reaches the end of the file, and starts the next file on a new page.  So, obvious solution would be remove any whitespace from the end of the chapter.  I was planning on trying this out tonight.

However, you say:
> There is no real way to fix this anyway (trust me i tried). Attempting to fix this will only cause major discrepancies between readers.

Before I duplicate what you tried, can I have some more details, please?

**Comment by dteviot** [comment] 2016-07-11 09:38
@typhoon71 @dreamer2908

Latest version in store (0.0.0.11) should fix problem with blank pages after the image gallery.   (And possibly at the end of chapters as well.  belldandu suggested removing the empty elements might have some unwanted side effects on some viewers. Can you please let me know how it works?

**Comment by dreamer2908** [comment] 2016-07-11 10:52
@dteviot 
I've tried version 0.0.0.11. Indeed, there's no longer blank pages after the gallery or at the end of chapters in Calibre ebook viewer. I've also converted some epubs to pdfs with Calibre. The result pdfs also have no blank pages.

If the removal of empty elements is limited to the ones around headings or images then I don't think there would be any unwanted effect.

Unrelated note: Ugh, apparently Calibre has problems with three dots in image filenames if I enable `--smarten-punctuation` option. Maybe I should report it to them when I stop being lazy.

**Comment by dteviot** [comment] 2016-07-11 20:01
@dreamer2908
Thanks for the feedback.

Have raised https://github.com/dteviot/WebToEpub/issues/46 for the Calibre issue.  Do you want to add more details on the probem? Or comment on the proposed solutions?

**Comment by dteviot** [comment] 2016-07-12 01:13
I believe the blank page problem is sorted.

**Closed by dteviot** 2016-07-12 01:13 UTC
Labels: bug

**Comment by belldandu** [comment] 2016-07-12 01:28
Oh neat
