### ISSUE TITLE
Text Color makes it hard to Read

### ISSUE THREAD

**Issue by JeremyStarten** [dteviot/WebToEpub#176] opened 2018-05-21 01:52 UTC
Suggestion:

Either have an option to not change text colors or maybe have the colors be given more contrast. When reading a book that's been changed to an epub, some colors are harder to read than others. Examples are colors like bright yellow and grey. This is so annoying because even increasing the brightness and what not doesn't help. 

An example of this in royal road is on [Queen of Devouring](https://royalroadl.com/fiction/11777/queen-of-devouring):
[Volume 3: Sealed World: Chapter 37.1 - Fight for your life](https://royalroadl.com/fiction/11777/queen-of-devouring/chapter/200290/volume-3-sealed-world-chapter-371-fight-for-your) - When reading the author note you will see the text here is borderline white. Although here it seems to be intentionally made to be hard to read, it has happened in real story chapters and it's annoying.
(like maybe to differentiate rarity)

**Comment by dteviot** [comment] 2018-05-22 01:11
It's not that simple.
If an author uses only one font colour, then WebToEpub will set all the font to black.  But, when the author uses a mixture of colours, it's not so clear what to do.  As the colours are probably there for a reason.
So, what WebToEpub does is find the font colour that is used the most, and makes all text using that colour black.  Any other colour is left alone.  What you're asking sounds like an option to force all font to black.  I'm going to say, I' not comfortable doing this.
Note, once you have an epub, you can use Calibre to force all colour to black.  See: https://www.reddit.com/r/kindle/comments/1buo2w/all_i_wanted_was_to_set_my_font_to_black/

**Comment by JeremyStarten** [comment] 2018-06-02 17:06
Ok it turns out my Epub reader also has a way to turn off colors so I guess it doesn't matter anymore.

**Comment by dteviot** [comment] 2018-06-02 21:03
Not a bug.  Won't fix.

**Closed by dteviot** 2018-06-02 21:03 UTC
