### ISSUE TITLE
blogspot issue

### ISSUE THREAD

**Issue by SpiralBaka** [dteviot/WebToEpub#379] opened 2020-09-08 17:50 UTC
I can't download from blogspot sites.
this site: https://www.sousetsuka.com/p/blog-page.html
shows this error:
-------------------
URL constructor: null is not a valid URL. convertToUrlOfOriginalSizeImage@moz-extension://36dafc7c-0df4-4d10-bad6-8f45512593a9/js/parsers/BlogspotParser.js:38:19
findCoverImageUrl@moz-extension://36dafc7c-0df4-4d10-bad6-8f45512593a9/js/parsers/BlogspotParser.js:88:36
populateUI@moz-extension://36dafc7c-0df4-4d10-bad6-8f45512593a9/js/Parser.js:120:29
processInitialHtml@moz-extension://36dafc7c-0df4-4d10-bad6-8f45512593a9/js/main.js:45:24
populateControlsWithDom@moz-extension://36dafc7c-0df4-4d10-bad6-8f45512593a9/js/main.js:211:27
onMessageListener@moz-extension://36dafc7c-0df4-4d10-bad6-8f45512593a9/js/main.js:16:36
-------------------
it won't even get the chapter list

=====================================
this site: http://skythewood.blogspot.com/p/gamers.html
can get chapter list, but when I try to "Pack EPUB", it shows:
-------------------
Fetch of URL 'http://xn--!-ck4bpb7ouhb/' failed with network error NetworkError when attempting to fetch resource.. onFetchError@moz-extension://36dafc7c-0df4-4d10-bad6-8f45512593a9/js/HttpClient.js:24:31
wrapFetchImpl/<@moz-extension://36dafc7c-0df4-4d10-bad6-8f45512593a9/js/HttpClient.js:152:45
-------------------
=====================================
this site: https://isekaimynoghra.blogspot.com/p/chapter-list.html
shows this error:
-------------------
URL constructor: null is not a valid URL. convertToUrlOfOriginalSizeImage@moz-extension://36dafc7c-0df4-4d10-bad6-8f45512593a9/js/parsers/BlogspotParser.js:38:19
findCoverImageUrl@moz-extension://36dafc7c-0df4-4d10-bad6-8f45512593a9/js/parsers/BlogspotParser.js:88:36
populateUI@moz-extension://36dafc7c-0df4-4d10-bad6-8f45512593a9/js/Parser.js:120:29
processInitialHtml@moz-extension://36dafc7c-0df4-4d10-bad6-8f45512593a9/js/main.js:45:24
populateControlsWithDom@moz-extension://36dafc7c-0df4-4d10-bad6-8f45512593a9/js/main.js:211:27
onMessageListener@moz-extension://36dafc7c-0df4-4d10-bad6-8f45512593a9/js/main.js:16:36
-------------------
and it also won't give the chapter list. 
although, if I select: "Advanced Options" -> "Manually Select Parser" -> "Default"
and configure that, I can download just fine.
=====================================

I haven't tried other sites. but, sousetsuka and skythewood are popular sites, please fix this.

EDIT: btw. the font size is all over the place. what's wrong with this? how do I fix this?

**Comment by dteviot** [comment] 2020-09-09 10:58
@SpiralBaka 
OK, the problem with sousetsuka and isekaimynoghra.blogspot.com is that they don't have images that can be used for a cover.
And there's a bug in the BlogSpot handling code for when this happens.
D'oh! My bad. I've committed a fix, however I have not posted the update to the Chrome or Firefox web stores as I've had a bunch of bugs reported in the last couple of days and I want post an update with them all fixed.  (Because Google only let me do 1 update every 5 days or so..)

The problem with http://skythewood.blogspot.com/p/gamers.html isn't my doing.
The error message is saying, WebToEpub tried to fetch a page from URL "http://xn--!-ck4bpb7ouhb/" but nothing responded.
Looking at the page, (or the list of chapters in WebToEpub) this is the URL for the "Available on Amazon" link.  If you try to go there manually, Chrome will tell you the site can't be reached.
When WebToEpub can't fetch a page with this error, by design it stops, and you'll need to fix. (In this case, Unselect "Available on Amazon".)

**Comment by SpiralBaka** [comment] 2020-09-09 16:47
ok. thanks for the answer. I'll wait for the update.

**Comment by dteviot** [comment] 2020-09-09 19:22
Reopen, to remind me to contact @SpiralBaka when update posted to Chrome & Firefox stores

**Comment by dteviot** [comment] 2020-09-10 20:21
@SpiralBaka
Updated version (0.0.0.119) has been submitted to Chrome and Firefox stores. Firefox store has new version available. Chrome will be (at least) a few days to finish review.

**Closed by dteviot** 2020-09-10 20:21 UTC
Labels: Priority: High, Status: Completed, Type: Bug
