### ISSUE TITLE
Can't download from Webnovel

### ISSUE THREAD

**Issue by pavan3999** [dteviot/WebToEpub#472] opened 2021-02-11 15:33 UTC
Error: Could not find content element for web page 'https://www.webnovel.com/book/magic-emperor-en_17549753605449805/nine-serenities-secret-records_47600300139271205'.     at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:479:23 & jpmtl.com too showing same error

kiwibrowser android also same in yandex browser.

**Comment by gamebeaker** [comment] 2021-02-11 20:50
I have no problem if i go to https://www.webnovel.com/book/magic-emperor-en_17549753605449805 and click Tabel of contents before clicking the plugin.

**Comment by pavan3999** [comment] 2021-02-11 23:18
so problem occurs in mobile browsers

**Comment by dteviot** [comment] 2021-02-12 00:04
If I put Chrome into mobile mode, (https://developers.google.com/web/tools/chrome-devtools/device-mode) WebToEpub fails.
Looking deeper, in mobile mode, it's using a different URL.  (https://m.webnovel.com/book/magic-emperor-en_17549753605449805/nine-serenities-secret-records_47600300139271205?from=catalog)
Note the hostname is "m.webnovel.com". 
The "m." prefix is common for sites, it denotes the mobile version of the site.  And it's not unusual for the mobile version to differ from the desktop version.

The weird thing is, the example URL from @pavan3999 had a hostname of "www.webnovel.com", suggesting it was fetching the desktop version of the chapter.
 

Also, for mobile site, the HTML for the chapter does not have the content, instead it's loaded by making a REST call.

**Comment by dteviot** [comment] 2021-02-12 00:06
@pavan3999
If you force desktop mode, does it behave?
https://www.howtogeek.com/176932/how-to-disable-the-mobile-version-of-a-website-on-your-phone/

**Comment by pavan3999** [comment] 2021-02-12 05:38
it's working if force to desktop site while using webtoepub too

**Comment by dteviot** [comment] 2021-02-12 06:42
@pavan3999
> so even extensions too have mobile view?

I'm sorry, I don't understand the question.

The problem is, some sites have a mobile view and a desktop view.  
If site detects you using a mobile browser, the site sends you to the mobile view.

And, as in the case of WebNovel, the mobile view is quite different from the desktop view. So, if I wanted WebToEpub to work for the mobile site, I'd basically have to treat it as a new site and write a whole new parser from scratch.  (It would probably take days to get a parser working for the WebNovel mobile site, )

I generally just build WebToEpub to handle a site's desktop view, and don't bother to support the mobile view.  Basically, building a parser for a site takes long enough as it is,

So, if your mobile browser tells the site it's a desktop browser, then site sends you to the desktop view, and WebToEpub will work.  And I don't have twice as much work to do.

**Comment by pavan3999** [comment] 2021-02-12 06:52
what i mean is it, if i turn on desktop site mode for webtoepub extension it's working fine while turn off desktop site mode it's not working (is webtoepub in mobile site mode??)

**Comment by gamebeaker** [comment] 2021-02-12 07:21
@pavan3999 ok i think i found a solution in kiwi browser Settings ->Website-Settings->(scroll down) Desktop mode by default-> "on" (Settings could have different names i have the app on German)
Go again to https://www.webnovel.com/book/magic-emperor-en_17549753605449805/nine-serenities-secret-records_47600300139271205 klick webtoepub and pack epub (Important only open webtoepub after Settings change). 
Now it works.

**Comment by pavan3999** [comment] 2021-02-12 07:30
@gamebeaker yeah i got that

**Comment by dteviot** [comment] 2021-02-12 07:51
@pavan3999
I'm not 100% sure what's going on, but here's what I hypothesize  is happening.

Assume Desktop mode is off.

WebToEpub tells the kiwi browser to fetch a chapter from WebNovel.
Kiwi browser makes the call to the WebNovel site. In the call, the browser sets the UserAgent header to tell the WebNovel the browser is a mobile browser,  and WebNovel sends a chapter back, thinking it's talking to a Mobile device.
Kiwibrowser hands the chapter to WebToEpub, and WebToEpub can't handle it.

Now when Desktop mode is on.

When Kiwibrowser asks for the chapter, UserAgent is set to "I'm a desktop", WebNovel responds as if it's talking to a desktop, and WebToEpub is happy.

So, it's not that WebToEpub has a mobile mode, it's how the browser hosting WebToEpub acts, or more precisely, what the kiwi browser tells the web site.

**Comment by pavan3999** [comment] 2021-02-12 07:57
ok good thanks for explanation, so using always on desktop site in accessibility in kiwi as @gamebeaker said and i checked

**Comment by dteviot** [comment] 2021-02-13 21:21
@pavan3999 
Closing issue.
Too much effort to support WebNovel's mobile view, and workaround exists.

**Closed by dteviot** 2021-02-13 21:21 UTC
