### ISSUE TITLE
[Error] Comrademao

### ISSUE THREAD

**Issue by stevedark01** [dteviot/WebToEpub#239] opened 2019-01-03 13:48 UTC
TypeError: Cannot read property 'getAttribute' of null
    at Function.getWdtnonce (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/ComrademaoParser.js:104:13)
    at Function.fakeFormData (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/ComrademaoParser.js:98:54)
    at ComrademaoParser.getChapterUrls (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/ComrademaoParser.js:34:36)
    at ComrademaoParser.onLoadFirstPage (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:302:14)
    at processInitialHtml (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:46:24)
    at populateControlsWithDom (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:205:9)
    at onMessageListener (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:16:13)
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
    at EventImpl.dispatch_ (extensions::event_bindings:387:35)

It can't get full chaps

**Comment by dteviot** [comment] 2019-01-03 19:32
@stevedark01 

Duplicate of https://github.com/dteviot/WebToEpub/issues/237

**Comment by dteviot** [comment] 2019-01-03 20:18
Updated version 0.0.0.64 has been released to Chrome store.  Should be available within a few hours.

**Comment by stevedark01** [comment] 2019-01-04 19:54
thanks

**Comment by dteviot** [comment] 2019-01-05 02:01
@stevedark01
> it select just 1page

I assume you meant that WebToEpub only lists the chapters on a single ToC page.  (e.g. 10 chapters.)
This is because, it's no longer possible to make a single HTTP call and get a list of all chapters, instead, need to request every ToC page. (And with 10 chapters per ToC page, thats 201 pages for Shoujo Grand Summoning. At 30 seconds per ToC page (on average), it takes over an hour to fetch the list of all chapters.)

If you can offer a solution, or I've not understood what you've requested please let me know.

**Comment by 3dycosmo** [comment] 2019-01-07 06:13
> @stevedark01
> 
> > it select just 1page
> 
> I assume you meant that WebToEpub only lists the chapters on a single ToC page. (e.g. 10 chapters.)
> This is because, it's no longer possible to make a single HTTP call and get a list of all chapters, instead, need to request every ToC page. (And with 10 chapters per ToC page, thats 201 pages for Shoujo Grand Summoning. At 30 seconds per ToC page (on average), it takes over an hour to fetch the list of all chapters.)
> 
> If you can offer a solution, or I've not understood what you've requested please let me know.

how about auto-generate starting URL
e.x.
https://comrademao.com/novel/possessing-nothing/
https://comrademao.com/novel/possessing-nothing/page/2
https://comrademao.com/novel/possessing-nothing/page/x..

**Comment by dteviot** [comment] 2019-01-07 19:24
@stevedark01 
> how about auto-generate starting URL

That doesn't work.  If you read all comments for https://github.com/dteviot/WebToEpub/issues/237, you will note that pages may have names like:
https://comrademao.com/mtl/shoujo-grand-summoning/shoujo-grand-summoning-chapter-fourth-floor-beat/

That said, I think possibly the solution is to update the progress bar as each ToC page is retrieved.  So, you'll at least see some progress as the list of chapters is loaded, even if it takes some time.

**Comment by 3dycosmo** [comment] 2019-01-08 10:41
> @stevedark01
> 
> > how about auto-generate starting URL
> 
> That doesn't work. If you read all comments for #237, you will note that pages may have names like:
> https://comrademao.com/mtl/shoujo-grand-summoning/shoujo-grand-summoning-chapter-fourth-floor-beat/
> 
> That said, I think possibly the solution is to update the progress bar as each ToC page is retrieved. So, you'll at least see some progress as the list of chapters is loaded, even if it takes some time.

Yeah, it doesn't work for chapters, but for the main pages for ToC to be retrieved. 
e.g.
https://comrademao.com/novel/possessing-nothing/ [retrieved 10 chaps, 432-END]
https://comrademao.com/novel/possessing-nothing/page/2 [retrieved 10 chaps, 422-431], etc
so the cumulative we get all (auto retrieved by generated ToC main pages, not the chaps itself, thanks.

**Comment by dteviot** [comment] 2019-01-17 19:50
Latest version (0.0.0.65) in store now fetches all ToC pages.
This can take many minutes, so the progress bar is updated while this is in progress.

**Closed by dteviot** 2019-01-17 19:50 UTC
