### ISSUE TITLE
https://boxnovel.com/

### ISSUE THREAD

**Issue by Lunatari23** [dteviot/WebToEpub#589] opened 2021-09-06 05:20 UTC
Good Afternoon 

there seems to be an issue with boxnovel.com 
this is coming up when i try to use the webtoepub 
TypeError: Cannot read property 'querySelectorAll' of null
    at BoxnovelParser.extractTitleImpl (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/BoxnovelParser.js:22:32)
    at BoxnovelParser.extractTitle (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:208:26)
    at BoxnovelParser.getEpubMetaInfo (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:262:31)
    at processInitialHtml (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:42:39)
    at populateControlsWithDom (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:222:9)
    at onMessageListener (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:16:13)

**Comment by dteviot** [comment] 2021-09-06 06:46
@Lunatari23 

Updated version (0.0.0.138) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

For my notes: Duplicate of https://github.com/dteviot/WebToEpub/issues/586

**Closed by dteviot** 2021-09-06 06:46 UTC
Labels: Status: Duplicate
