### ISSUE TITLE
[Feature Request] Option to skip error messages

### ISSUE THREAD

**Issue by toshiya44** [dteviot/WebToEpub#133] opened 2017-09-12 00:48 UTC
Badly structured webpages often produce a lot errors and it becomes impractical to read and click OK on all of them to finally get the epub. So it would be useful to have an option like "Skip all error messages during content fetching".

After the epub processing is done (or halted due to errors), show a message like "n errors have occurred" and print the error log in a text file regardless of whether the option to print error logs have been checked or not.

**Comment by dteviot** [comment] 2017-09-12 00:54
@toshiya44 
Would this be a checkbox in the Advanced Options, or a button on the error page itself?

**Comment by toshiya44** [comment] 2017-09-12 02:00
I think it should be in Advanced Options as well as the first error page the user encounters, so that they know this option exists.

**Comment by dteviot** [comment] 2017-09-20 20:00
@toshiya44 
> Option to skip error messages

This is proving much more difficult than anticipated.
Can you confirm that the issue is large numbers of this sort of error message?  Or is it one of the others.

>Warning, unable to convert chapter 'Martial God Asura Chapter 1450-1454' from 'http://novelplanet.com/Novel/Martial-God-Asura/c1450-1454?id=190940' to valid XHTML. Your epub viewer may fail when viewing that chapter. You may need to fix the chapter manually with Calibre.

I think the solution may be to accumulate all errors of this type as they occur, then present as a single dialog at the end.

**Comment by toshiya44** [comment] 2017-09-20 23:42
I had these kinds of errors in mind when I wrote the issue

```
Fetch of URL 'https://example.com/randomstuff/' returned HTML, expected an image.
```

and general network errors.

---------------------------

> I think the solution may be to accumulate all errors of this type as they occur, then present as a single dialog at the end.

That works too, but it may need to be truncated to a certain length to avoid issues in cases where too many errors are thrown. The browser might freeze up if the page is too big.

**Comment by dteviot** [comment] 2017-09-23 23:32
@toshiya44
Actually, that error doesn't mean the web page is badly structured. 
It means the parser doesn't know which image to pick from a page of images.

For example, When you click on a Baka Tsuki image, a web page with a collection of images is returned.
The parser can recognise these pages and fetch the appropriate image.
However, when you get this error, the parser doesn't recognise the HTML's format.
Need to fix this by creating a new ImageCollector and provide a selectImageUrlFromImagePage(dom) function for the page.

If you can give me the URL you're having problems with, I'll see what I can do to fix.

That said, I've committed code to Experimental Tab branch that should consolidate these warnings to single page.
Please let me know what you think of it.

**Comment by toshiya44** [comment] 2017-09-24 05:48
Here's an example URL https://bakapervert.wordpress.com/magika-vol-1-illustrations/


![image](https://user-images.githubusercontent.com/20046789/30779844-0ae00e30-a0ca-11e7-9137-fd264dd1e814.png)

Nice. Can you please move the "ok" button to the top and make it slightly bigger?

**Comment by dteviot** [comment] 2017-09-27 07:24
@toshiya44
The following changes have been checked into Experimental Tab branch
* Buttons on warning dialog enlarged and moved to top of dialog
* Images on Bakapervert should no longer generate warning messages.

Please let me know if these are satisfactory.

**Comment by toshiya44** [comment] 2017-09-28 00:01
Thanks. 

Tested on FF 55.0.3 and 57.0.b3


On FF57, I got a message in the console after adding the extension.  
`addons.webextension.WebToEpub@Baka-tsuki.org	WARN	Please specify whether you want browser_style or not in your browser_action options.`

I think it's asking you to add a parameter to the manifest  
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/browser_action

**Comment by dteviot** [comment] 2017-09-28 06:04
@toshiya44
I'm running same version of Firefox, but don't get the problem.
Adding browser_style doesn't seem to cause any problems with Chrome, so I've added it anyway.

**Closed** 2017-10-07 20:41 UTC
