### ISSUE TITLE
Please add site en.novelxo.com

### ISSUE THREAD

**Issue by AngelBurn** [dteviot/WebToEpub#1028] opened 2023-08-01 08:44 UTC

**Comment by dteviot** [comment] 2023-10-14 02:50
Duplicate of https://github.com/dteviot/WebToEpub/issues/1021

**Comment by dteviot** [comment] 2023-10-14 02:53
@AngelBurn 
Duplicate of https://github.com/dteviot/WebToEpub/issues/1001. 
Unfortunately, site is scrambling and encoding the text to prevent things like WebToEpub working.
I can't help you.

**Closed by dteviot** 2023-10-14 02:53 UTC
