### ISSUE TITLE
website request

### ISSUE THREAD

**Issue by ch7black** [dteviot/WebToEpub#257] opened 2019-03-26 09:15 UTC
please add mtled-novels.com. it is same like lnmtl just need the raw/ chinese text to be removed

**Comment by dteviot** [comment] 2019-03-27 04:03
@ch7black
Duplicate of https://github.com/dteviot/WebToEpub/issues/255

**Comment by dteviot** [comment] 2019-03-28 04:17
Updated version (0.0.0.70) which has been uploaded to Chrome web store.

**Closed by dteviot** 2019-03-28 04:17 UTC
