### ISSUE TITLE
Minor visual annoyances

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#422] opened 2020-11-21 17:01 UTC
Hi, 

I'm (finally) using webtoepub on a more recent firefox (developer, v84.0b3 today) an there's something I noticed:

![immagine](https://user-images.githubusercontent.com/1866248/99882869-bd84b300-2c23-11eb-9c4f-611f0cc17171.png)
As you can see the red area is not used and the links are forced to use a smaller area; you can't grab the border to make it bigger either. Can this be fised? Thanks.

Another little thing I noticed is that the links are no more visible in the main window: can they be made visible again? Thanks.

**Comment by dteviot** [comment] 2020-11-21 22:47
@typhoon71
> As you can see the red area is not used and the links are forced to use a smaller area; you can't grab the border to make it bigger either. Can this be fised? Thanks.

I'll look into it.

>  I noticed is that the links are no more visible in the main window: can they be made visible agai

Tick the "Show URLs of Chapters" check box to the left of the "First Chapter" drop down list.

**Comment by typhoon71** [comment] 2020-11-22 09:04
I totally didn't see the  "Show URLs of Chapters" option... I even went in the Advanced options to search for a setting... that was just staring me! Thanks.

**Comment by dteviot** [comment] 2020-11-24 08:55
@typhoon71
I'm a complete noob when it comes to CSS.
However, I think it might have a partial fixed for the problem.
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Note, I haven't committed the change to GitHub yet, I'm not really happy with it. So you'll need to use the above zip.  Note the simplified steps for loading the zip into Firefox.

**Comment by typhoon71** [comment] 2020-11-24 12:49
Tested the Firefox version: the window is resizable now, but:
- it starts small, limited by theouter frame (or what's it's called)
- you can't resize to full screen size

Also noticed that in the main window if you enable "show url" the line becames bigger than the scree if the link is long; maybe cutting it would be more pleasing.

**Comment by dteviot** [comment] 2020-11-24 18:48
@typhoon71
> it starts small, limited by theouter frame (or what's it's called)

I did say it was a partial fix, I'm still trying to figure that bit out..

> you can't resize to full screen size

It should be possible (works for me on Chrome, I didn't test on Firefox)  at the bottom of the textarea's scroll bar, drag that.
![ResizeHandle](https://user-images.githubusercontent.com/5157081/100138209-8a2b7800-2ef2-11eb-9290-26b4e32cf533.png)

>  the line becames bigger than the scree if the link is long

Please provide the ToC URL so I can reproduce.

**Comment by typhoon71** [comment] 2020-11-24 19:14
oh, I was just reportingwhat happened here, I know nothing about css so I can't really "complain" ;)

if I drag the bar it stops at a certain point (I meant the full width of the screen, not fullscreen)

example affected url:
"https://www.monclick.it/vendita_monitor-pc_Philips,AOC,Dell+Technologies/descr3_risoluzione_1920-x-1080,2560-x-1440/idrange2_752_pollici_20-30/quicklink_prontaconsegna/page_1?prezzoMax=500&prezzoMin=100&ordinamento=pricedown&pagesize=50&vista=lista"

ok, it's not a place I'd use webtoepub..., but it should be a good example, "maybe" only not a "real use case".

**Comment by dteviot** [comment] 2020-11-27 07:39
@typhoon71 
Latest test version should open the "manually edit chapter links" window much wider..

**Comment by typhoon71** [comment] 2020-11-27 09:13
Tested it on firefox, now the "Edit Chapter URLs" window is perfect. Thanks a lot.

What about the "Show URLs of Chapters" in the main window option with long links?
Would it be possible to fix that issue too?

**Comment by dteviot** [comment] 2020-11-28 23:45
@typhoon71 
>  in the main window option with long **links?

It's on my to do list.

**Comment by dteviot** [comment] 2020-11-29 02:12
@typhoon71
> Also noticed that in the main window if you enable "show url" the line becames bigger than the scree if the link is long; maybe cutting it would be more pleasing.

OK, I tried to reproduce this error by manually editing the URLs to be very long.
Result was, on Chrome and Firefox, get a horizontal scroll bar to see all the URL.
I'm happy with this behavior.  The problem with "trimming the URLs is it's not always possible to know what part of the URL is not important.  Sometimes I want to see the host name, Other times, the vital part of the path is the start, not the end.  e.g. When Volume is part of the path, and the chapters repeat.

**Comment by typhoon71** [comment] 2020-11-29 15:50
Makes sense, not like you'll find a lot of those superlong link.

**Comment by dteviot** [comment] 2020-11-30 07:44
@typhoon71
Updated version 0.0.0.124 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in 3 to 7 days, once it finishes review.

**Closed by dteviot** 2020-11-30 07:44 UTC
Labels: Status: Completed
