### ISSUE TITLE
Mtlarchive is having some 403 issues again.

### ISSUE THREAD

**Issue by Franzeeee** [dteviot/WebToEpub#1439] opened 2024-08-24 05:29 UTC
The mtlarchive.com is having some 403 errors again. Even if i already did the captcha and already logged in, it's still giving me the 403 error.

**Comment by Kiradien** [comment] 2024-08-24 10:22
Looks like we've hit an issue with sending the cf cookies again; not entirely sure why this is hitting specifically on mtlarchive. I'll try to look into this in the evening if no one picks it up. The default request cookie appears to have cf_clearance after a new line - might be the reason.
![image](https://github.com/user-attachments/assets/ddd7eb1b-eee3-49ae-ac0b-811943b0722e)

**Comment by gamebeaker** [comment] 2024-08-24 10:40
@Franzeeee Firefox works, Chrome is broken.

**Comment by gamebeaker** [comment] 2024-08-24 12:26
Looks to me like it is going to be a bigger problem. I just tested [https://www.scribblehub.com/](https://www.scribblehub.com/) and it also stopped working.
At the moment i am not sure what the problem is.
It looks like something changed with the cookies:
let name1 = "cf_clearance";
cookies = await chrome.cookies.getAll({name: name1});
returns all "old" wesites with cloudflare cookie.
Example i get a cookie for discord -> visit discord -> execute js again now the cookie for discord isn't returned anymore.
It looks to me like cloudflare changed some flags for the cookie cf_clearance:
old:
![image](https://github.com/user-attachments/assets/defa70e6-7bb3-43db-8c3e-bcb3fea26a6d)
new:
![image](https://github.com/user-attachments/assets/6b48f764-5baf-4bca-8eb1-21bf6075412c)

**Comment by Kiradien** [comment] 2024-08-24 13:48
> It looks like something changed with the cookies:

It looks like the problem is in Chrome rather than the cookies themselves; I've been digging through the setting method and the following request returns an empty array.
``` let cookies = await chrome.cookies.getAll({partitionKey: {topLevelSite: topLevelSite}}); ```

**Comment by gamebeaker** [comment] 2024-08-24 18:47
I have opened an issue with chromium: https://issues.chromium.org/issues/361862746

**Comment by gamebeaker** [comment] 2024-08-24 23:04
@Kiradien @dteviot would be cool if you guys could vote "I am impacted" in the issue tracker: https://issues.chromium.org/issues/361862746

**Comment by gamebeaker** [comment] 2024-08-25 12:06
@Franzeeee 
Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
*  https://mtlarchive.com/novel/traveling-through-thousands-of-realms-starting-from-obtaining-the-ten-marvel-rings

**Comment by gamebeaker** [comment] 2024-09-08 14:42
Chrome code fix got merged [https://issues.chromium.org/issues/361862746](https://issues.chromium.org/issues/361862746).

**Closed** 2024-09-26 08:51 UTC
Labels: Status: Completed
