### ISSUE TITLE
https://hellping.org/

### ISSUE THREAD

**Issue by Flwk** [dteviot/WebToEpub#505] opened 2021-04-06 22:34 UTC
Hello

Is it possible to add this website  : https://hellping.org/

Here [is ](https://hellping.org/angel/angel-wn-chapter-1/)an example of table of contents.

Thanks you for your hard work !

**Comment by dteviot** [comment] 2021-04-07 07:32
@Flwk

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by Flwk** [comment] 2021-04-07 13:30
Hello

When i try to do it for [this](https://hellping.org/angel/) novel (for example), i don't get the chapters : 

[WebToEpub.pdf](https://github.com/dteviot/WebToEpub/files/6271894/WebToEpub.pdf)

You can see it on the pdf file, there isn't the chapters of the novel, but just the novels that are available
Here is the [epub ](https://drive.google.com/file/d/1yAam6ZyXwH_Xt1dlL_tn2TLgW8bpHJJs/view?usp=sharing) file generated

Thanks in advance

**Comment by dteviot** [comment] 2021-04-07 19:37
@Flwk 
That would be because the first few stories I checked https://hellping.org/magdala-v1/, https://hellping.org/magdala-v2/
did not have TOC on the page. So, I fell back to the menu.
But I'll see what I can do.

**Comment by dteviot** [comment] 2021-04-08 08:32
@Flwk

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by Flwk** [comment] 2021-04-08 11:08
Hello

Here is an error, it download a few chapters and stop :

Error: Could not find content element for web page
'https://hellping.org/wp-admin/post.php?post=4977&action=edit&classic-editor'.
    at chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/Parser.js:495:23
    at async Promise.all (index 0)


So i don't know where is the problem, i'll try more times to see

**Comment by dteviot** [comment] 2021-04-08 19:47
@Flwk
Error means WebToEpub can't find the HTML element with the chapter content on a page.  (This means one of the pages has a different format)  The page will be in the last 8 pages fetched.  Look at the list of URLs that have been fetched and the problematic page will be one of the last 8.  My guess is the list of URLs probably contains one that is to a page that's on a different Site to Hellping.

**Comment by dteviot** [comment] 2021-04-12 22:09
@Flwk 
I'd really like to close this out so I can post updated versions of WebToEpub.
Any chance you can give me the URL to the ToC, and I'll see if I can reproduce the problem?

**Comment by Flwk** [comment] 2021-04-13 12:50
It works well ! 

Thank you very much !

**Comment by dteviot** [comment] 2021-04-13 19:25
Reopening so I can notify @Flwk when updated version is posted to Chrome and Firefox stores

**Comment by dteviot** [comment] 2021-04-15 08:33
@Flwk
Updated version (0.0.0.130) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.

**Closed by dteviot** 2021-04-15 08:33 UTC
Labels: Status: Completed
