### ISSUE TITLE
69shu.com doesn't work anymore

### ISSUE THREAD

**Issue by Iadders** [dteviot/WebToEpub#1058] opened 2023-08-29 10:38 UTC
It redirects to 69shuba.com

Text is all nonsense

![Screenshot_20230829_153631_Moon+ Reader Pro](https://github.com/dteviot/WebToEpub/assets/84446964/06324bc7-4b78-4f17-b398-eae55d09299d)

**Comment by dteviot** [comment] 2023-08-29 19:49
@Iadders 

Duplicate of https://github.com/dteviot/WebToEpub/issues/1045

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by dteviot** [comment] 2023-09-11 08:13
@Iadders 

Updated version (0.0.0.155) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.

**Closed by dteviot** 2023-09-11 08:13 UTC
Labels: Status: Duplicate, Status: Completed
