### ISSUE TITLE
download problem

### ISSUE THREAD

**Issue by kaikai55555** [dteviot/WebToEpub#219] opened 2018-11-01 15:31 UTC
After Using web to epub, choosing chapters, packing, and choosing download destination, when downloading, it reads "Failed-Network error"

**Comment by dteviot** [comment] 2018-11-01 19:28
@kaikai55555
Please forgive me as I paraphrase what I think you've said.  I want to make sure I've understood your description of the problem.  Which is:
1. You go to a web site.
2. You open WebToEpub, and select the chapters you want.
3. You click on the "Pack Epub" button
4. You see the chapters getting fetched.  (A tick appears beside each chapter in the list.)
5. The "Download" dialog appears, asking for the name to save the EPUB as.
6. After clicking 'OK" an error appears with text "Failed-Network error".

**Question One**
Have I correctly described the problem?

**Question Two and Three**
Does this problem occur for every web page you try to convert?  (I'll assume it does.)
Please give me the URLs of two stories that don't work.  (I'd like to confirm that I can successfully download them, so that I know it's not something odd about the sites themselves.)

**Preliminary Hypothesis**

I'll assume you're using Chrome.  Note, if you're not using Chrome or Firefox, then I should point out I only support WebToEpub on Chrome and Firefox, I don't have the resources to support other Browsers.
Note, if you're running Chrome, you might like to try installing Firefox, loading WebToEpub for Firefox from https://addons.mozilla.org/en-US/firefox/addon/webtoepub-for-baka-tsuki and see if that works.

**Question Four and Five**
What web browser (Chrome/Firefox/Chromium/Brave/Vivaldi etc). are you using?  What Version?

Assuming you're running a recent version of Chrome, then I suspect the problem is to do with the configuration of your Web Browser.

The most likely possibility is you have some other extension loaded that is interacting with WebToEpub, and causing the saving of the EPUB to the downloads area of disk to fail.  If you have any other extensions loaded, then to confirm this hypothesis
1. Disable **ALL** extensions.
2. Re-enable the WebToEpub extension
3. Use WebToEpub to try to convert a web page to EPUB.  I'd suggest tying a single chapter from https://www.royalroad.com/fiction/21220/mother-of-learning (because I know it works.)
4. If it works, try enabling the other extensions one by one and running WebToEpub again until it fails.  This should allow you to identity the conflicting extension.
5. If you find the conflicting extension, please let me know.

If you don't have any other extensions or the problem exists with all other extensions disabled, then next thing to check is the Browser's configuration.

**Question Six and Seven**
Are you running Chrome in any special mode?  (e.g. Incognito)
Have you changed any Chrome settings from their defaults?

**Comment by dteviot** [comment] 2018-11-01 19:32
@kaikai55555
Additional questions.  Where are your trying to save the epub to?  Is it the standard Downloads directory, or somewhere different?

**Comment by kaikai55555** [comment] 2018-11-02 19:58
question 1: correct
Question 2 and 3: Yes, every webpage, urls are:
https://www.ehmed.xyz/very-pure-and-ambiguous/
https://hilirivsfantasy.blogspot.com/p/parameter-remote-controller.html
Question 4 : Chrome
Question 5: Latest version (reinstalled after first failed attempts)
Question 6: no special mode
Question 7: only difference is continue where I left off on startup

**Comment by dteviot** [comment] 2018-11-03 00:31
Can you confirm that you either have no other extensions, or you tried disabling all the other extensions?

For what it's worth, from your description it sounds like the problem is occuring when WebToEpub is trying to write the epub file to disk.
As this works for me (and lots of other people) there's something about your PC (or Chrome) that's making the save to disk fail.
Trying to figure out what it is, is not easy.  

Most of the times I've had people report this problem, it's been due to conflicting extensions.
However, based on the fact you didn't say anything about them, I'll assume you have no other extensions loaded.

Given that you've re-installed Chrome, I'll also assume that Chrome itself isn't the problem.
Therefore, I'm left with there's something on your PC that's causing the problem.
Are you running any anti-virus or other security software?

From https://productforums.google.com/forum/#!topic/chrome/7XBU6g6_Ktc, there's a few more suggestions.
* Try changing your download destination folder within Chrome.
* Try downloading the file in a Chrome incognito window. If you no longer see the error message, you might have an issue with a Chrome extension. Learn how to disable them here.
* Check to see if any antivirus or firewall programs on your computer may be blocking the download by turning them off temporarily. If you can download files when the firewall is off, you may need to create an exception in your antivirus or firewall settings.
* Create a new user profile. If you no longer see an issue with downloading files, your browser profile could be corrupt

**Comment by dteviot** [comment] 2019-10-25 04:04
Closing due to no further response from original opener.  If there's a problem, let me know and I'll re-open

**Closed by dteviot** 2019-10-25 04:04 UTC
Labels: Status: Help Wanted, Type: Bug

**Comment by Sam5556-C** [comment] 2025-02-16 17:11
Since last week webtoepub can't download long files of Wattpad after downloading a few chapters it stops showing error

**Comment by gamebeaker** [comment] 2025-02-16 17:55
@Sam5556-C please open new issue with the error message.
