### ISSUE TITLE
Request to support site https://www.lightnovelworld.com

### ISSUE THREAD

**Issue by ragen123** [dteviot/WebToEpub#376] opened 2020-09-07 18:27 UTC
Hi,
currently you can only create epub of only one page displayed in ToC.
https://www.lightnovelworld.com/novel/supreme-magus-webnovel
Thx

**Comment by dteviot** [comment] 2020-09-07 19:50
@ragen123 
I can't seem to reproduce your problem.  What I did
1. Open web page https://www.lightnovelworld.com/novel/supreme-magus-webnovel in Chrome
2. Click on the WebToEpub icon
3. Click "Pack Epub"
4. Took a while to pack (network traffic shows site giving warnings about load.  I'd suggest clicking on the "Advanced" button and setting Max web pages to fetch simultaneously to 1) But got there in the end
5. Epub seems to be fine. Copy here https://drive.google.com/file/d/1Mmcc3axuJsKWJzmUXmm-8mpiVrPm0If8/view?usp=sharing

**Comment by dteviot** [comment] 2020-09-09 11:12
@ragen123
Perhaps I wasn't clear.  I can't reproduce your problem.  If I can't reproduce it, I can't fix it.
You need to tell me the steps you do to make it happen.  In sufficient detail I can duplicate the steps.

**Comment by ragen123** [comment] 2020-09-13 14:53
Sorry, for the late reply.
Creating epub works, but it only creates an epub of only chapters displayed on the first page (94 chapters out of 840ch).
Right now I have to create 8 epubs of 94 chapters and merge them together in calibre.

**Comment by dteviot** [comment] 2020-09-14 08:32
@ragen123
It has failed for me now, due to them changing the site.
I've committed a fix, but won't be submitting to Chrome and Firefox stores for (probably) a few days, as there are other issues to deal with.

**Comment by dteviot** [comment] 2020-09-25 09:09
@ragen123
Updated version (0.0.0.120) has been submitted to Chrome and Firefox stores. Firefox store has new version available. Chrome will be (at least) a few days to finish review.

**Closed** 2020-09-25 09:11 UTC
Labels: Status: Completed
