### ISSUE TITLE
Certain Pages giving Fetch Fail errors on image collector.

### ISSUE THREAD

**Issue by belldandu** [dteviot/WebToEpub#94] opened 2016-12-17 08:18 UTC
https://www.baka-tsuki.org/project/index.php?title=Toaru_Majutsu_no_Index:Volume_SP

Once the fetch fail happens all the images are nowhere to be found in the xhtml files within the epub.

ATM im unsure as to whats causing this but there could be other pages that do this as well.

**Comment by belldandu** [comment] 2016-12-17 08:28
Side note. Similar but not the same as #13

**Comment by dteviot** [comment] 2016-12-20 18:30
Unable to reproduce with given link.
I will probably need to build a test case to reproduce.

**Comment by dteviot** [comment] 2016-12-21 19:02
@belldandu
Any chance you can email me a copy of the malformed epub?  An examination may give clues about where the bug is.

**Comment by dteviot** [comment] 2016-12-24 21:21
@belldandu
I've not been able to reproduce the behavior you report.
Even when one of the images fails to download:
1. The following images are downloaded and placed in the \OEBPS\Images directory.
2. The XHTML files are correctly linked to the images,

I will need the malformed epub to make any more progress.

**Comment by belldandu** [comment] 2017-03-12 22:32
@dteviot sorry I've been really busy since December and was even involved in a hit and run, so i've been mostly away from the internet entirely. As for the malformed epub i'll have one for you later tonight. Also the best way to reproduce would be to run it on wayback archive pages as those will definetly give fetch fail errors after a few runs. It's also possible that this has been fixed in more recent versions...

and i take that back
![screenshot 75](https://cloud.githubusercontent.com/assets/5639384/23836656/158558f2-0752-11e7-893c-2bcd0740d10a.png)

When i click ok or tab away it ends up doing this too now

![screenshot 76](https://cloud.githubusercontent.com/assets/5639384/23836668/3c441bae-0752-11e7-86bf-c8c38a9823eb.png)

**Comment by belldandu** [comment] 2017-03-12 22:32
Epub doesnt even save.

**Comment by belldandu** [comment] 2017-03-12 22:33
![screenshot 77](https://cloud.githubusercontent.com/assets/5639384/23836679/69d32c04-0752-11e7-99eb-d2ced3dac274.png)

**Comment by belldandu** [comment] 2017-03-12 22:36
Using the latest version approved by firefox which is 0.0.0.24 https://addons.mozilla.org/en-US/firefox/addon/webtoepub-for-baka-tsuki/

**Comment by buthub** [comment] 2017-07-09 22:15
Not sure if the problem is the exact same, but I also noticed that for illustration pages,
e.g. https://paichuntranslations.com/tdditkc6yw/v1-illustrations/
it will grab the smaller image, but not the larger one that it links to.  Not a problem per se, but it would be nice if it could follow the link from each image and download the larger image that's one that page, instead of the tiny ones.

Similar problem occur if it leads to pictures on imgur.com (and probably others).  Thanks.

**Comment by dteviot** [comment] 2017-07-12 03:55
@buthub

I thought I'd fixed the issue with Imgur images.  Can you please give me a link that has the problem? (I'm after URL of the the HTML page that links to images on Imgur, not the URL of the images on Imgur.)

**Comment by dteviot** [comment] 2017-07-25 19:32
@belldandu
Seems to work fine when document being collected has multiple web pages:
e.g. I go to https://zirusmusings.com/ldm-toc/
The following chapters have links to images that are no longer there.
- Chapter 106 – Meat’s Name and Making the Ring https://zirusmusings.com/ldm-ch106/
- Chapter 147 – Extra: Ichika and the Bar’s Slots https://zirusmusings.com/ldm-ch147/
- Omake 4 – New Year’s Day https://zirusmusings.com/ldm-omake4/

Failure to fetch these images still results in all other pages being fetched, and images are visible in final epub.
That said, I'm now wondering if problem might be with the Baka-Tsuki parser only.

**Comment by dteviot** [comment] 2017-10-10 09:25
Closing.  Fix for https://github.com/dteviot/WebToEpub/issues/128 should also fix issue with failures to Fetch by Image Collector.

As @buthub has not supplied sample URLs to display issue with reduced size images, I can't progress.

**Closed by dteviot** 2017-10-10 09:25 UTC
Labels: Priority: Medium, Status: Pending, Type: Bug
