### ISSUE TITLE
Ziru's Musings parser can't get content

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#184] opened 2018-06-16 08:14 UTC
On this webpage: "https://zirusmusings.com/fh-toc/" --> if you try to grab it doesn't find the links.

Also, if you manually insert the links in the links editor, it can't find content at all.

Error: Could not find content element for web page 'https://zirusmusings.com/fh-illustrations/'.
    at chrome-extension://pdjgnlommckobgkiialndbmakmkebdjp/js/Parser.js:399:23

The example is with the first link, but it happens with the other links too.

Issue appears both on chrome and chromium (edited, was firefox).

**Comment by dteviot** [comment] 2018-06-17 00:40
@typhoon71
You may have noticed the site has changed its layout.
It even says so in a notice on the top right of most screens. :)
Changes.
1. Different tag for content.
2. Images are lazy loaded.

Parser for site has been updated on the Experimental Tab branch.
Please let me know if you find any issues.
Especially check it is getting all images,  The lazy loading proved to be a pain.

**Comment by typhoon71** [comment] 2018-06-17 07:07
Yes, the layout changed and that's when I stopped being able to grab stuff.
I did test the addon on 3 novels (Forsaken Hero, Cheat Receptionist, Magus of Genesis).
Almost perfect (I know lazy loading can be painful, and I don't think it matters if there's just a couple of images on the page anyway).
The results:

1) The images and content are grabbed correctly.
2) If there is an "image related error" the epub doesen't get saved, only the error log does.

**Cheat Receptionist, vol 2**
Fetch of URL 'https://discordapp.com/invite/YSBTnHe' returned HTML, expected an image.

**Magus of Genesis**
Fetch of URL 'https://www.patreon.com/join/811780/signup?client_id=zys-bvYb9llLfVLbTwcQbIIAA4_yz0axjQs48jrtJET3AVQlK5iAUDhAeBk97twG&state=YToyOntzOjE4OiJmaW5hbF9yZWRpcmVjdF91cmkiO3M6NDA6Imh0dHBzOi8vemlydXNtdXNpbmdzLmNvbS9tZzItaW50ZXJsdWRlMi8iO3M6MTM6InBhdHJlb25fbm9uY2UiO3M6MzI6IjAzMTEwYTdkNzAyNjEyMGU1NjY2NmY0ZTBmZWI4MTg4Ijt9&response_type=code&amt=1.0&redirect_uri=https%3A%2F%2Fwww.patreon.com%2Foauth2%2Fbecome-patron%3Fredirect_uri%3Dhttps%253A%252F%252Fzirusmusings.com%252Fpatreon-authorization%252F%26client_id%3Dzys-bvYb9llLfVLbTwcQbIIAA4_yz0axjQs48jrtJET3AVQlK5iAUDhAeBk97twG%26min_cents%3D100%26response_type%3Dcode%26state%3DYToyOntzOjE4OiJmaW5hbF9yZWRpcmVjdF91cmkiO3M6NDA6Imh0dHBzOi8vemlydXNtdXNpbmdzLmNvbS9tZzItaW50ZXJsdWRlMi8iO3M6MTM6InBhdHJlb25fbm9uY2UiO3M6MzI6IjAzMTEwYTdkNzAyNjEyMGU1NjY2NmY0ZTBmZWI4MTg4Ijt9&utm_source=https%3A%2F%2Fzirusmusings.com&utm_medium=patreon_wordpress_plugin&utm_campaign=811780&utm_term=&utm_content=post_unlock_button' returned HTML, expected an image.

**Comment by dteviot** [comment] 2018-06-17 19:49
@typhoon71 
>If there is an "image related error" the epub doesen't get saved, only the error log does.

I'm unable to reproduce this problem.  
Can you confirm the epub is not created?  (Have you checked the downloads directory to be sure?)
Are you using Firefox or Chrome?
Do you have any special settings in Firefox/Chrome?
I assume you've turned on WebToEpub's "Write error messages to file" option.  Does turning it off help?

**Comment by typhoon71** [comment] 2018-06-17 21:01
- I can confirm the epup is not created (nothing in the download directory, I checked)
- I'm using chrome 66.
- No special settings, it's a new chrome install (old one broke).
- If I turn off "Write error messages to file" there's no log saved (obviously), but no epub.

_-> You can check this <a href="https://pirateyoshi.wordpress.com/gcr2-prologue/">Full</a>, it's the link that causes the error in Cheat Receptionist._

**Comment by dteviot** [comment] 2018-06-18 01:05
@typhoon71 
I'm still not able to reproduce the problem
Here's the steps I go through.

1. In chrome, I go to https://zirusmusings.com/gcr-toc/
2. I click on the WebToEpub button on toolbar
3. Click the "Unselect All" button
4. Check button for URL https://pirateyoshi.wordpress.com/gcr2-prologue/
5. Click "Pack EPUB"
6. Screen shows "Fetch of URL 'https://discordapp.com/invite/YSBTnHe' returned HTML, expected an image.", but I also see the download appear at the bottom of the screen

Can you tell me how these steps differ from what you did?

Some other things to try/questions:
1. After opening WebToEpub, open the developer tools window and go to the console tab.  Then when do "Pack Epub" does anything show?
2. If you use the extension in Firefox, does it work correctly?
3. What other plug-ins do you have loaded?
4. Did the "no saving epub file" only appear with the latest version of WebToEpub.  (Which is strange to me, as I didn't make any changes to the file saving code.)
5. Do you have same problem with other web sites? e.g.Can you reproduce problem with https://github.com/dteviot/WebToEpub/issues/165  (Note, this should have been fixed.)

Also "Fetch of URL 'https://discordapp.com/invite/YSBTnHe' returned HTML, expected an image." should not be a fatal error.
It's really just informative.

**Comment by typhoon71** [comment] 2018-06-18 16:24
1) I edited my comment, I tested it on chrome and chromium, not with ffox. My bad.
2) It works fine in ffox 61.0b14 and even with ffox 56 (temp addon).
3) It does not work on chome or chromium but I noticed that if I change this setting in those browser it does works:

4) #165 would fail if I don't turn that setting on.

**Comment by dteviot** [comment] 2018-06-18 19:35
@typhoon71
Closing this issue as the problem with Ziru's Musing parser has been fixed, and I've created https://github.com/dteviot/WebToEpub/issues/185 for Epub file not saving.

**Closed by dteviot** 2018-06-18 19:35 UTC
Labels: Priority: High, Status: In Progress, Type: Bug
