### ISSUE TITLE
Cover image aspect ratio is broken

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#70] opened 2016-08-26 05:45 UTC
I wanted to ask something regarding (cover) image(s) aspect ratio.
I made an epub from: https://www.baka-tsuki.org/project/index.php?title=Toaru_Majutsu_no_Index:NT_Volume16&printable=yes.
The cover image is correctly shown in calibre, but when exported to pdf it's resized ignoring aspect ratio completely.
It happens with any novel I tried on bakatsuki, and sometime it stretches smaller cover images (on other sites).
I'd like to ask what is causing it, if it's a calibre bug or something else.
The other images seems fine, but since their aspect ratio is similar to a single page maybe I'm not noticing it.

**Comment by dteviot** [comment] 2016-08-27 22:03
I'd check that the dimensions in the <svg> and <image> tag for the image match the actual image.  If they do, then the problem is either in calibre creating the pdf, or the pdf itself and you should contact the calibre team.  I can't help you with pdf.  I don't have the time to study it.

**Comment by dteviot** [comment] 2016-09-22 20:15
@typhoon71 
I'm closing this.  I believe it's an issue with Calibre pdf generation.  Feel free to re-open if you disagree.

**Closed by dteviot** 2016-09-22 20:15 UTC
Labels: bug in reader, wontfix

**Comment by typhoon71** [comment] 2016-09-23 06:01
OK.
Better putting resources (your time) torward more relevant issues.
It could also be an option buried somewhere in calibre, which I find is a bit messy.
