### ISSUE TITLE
Missing chapers from webnovelpub.com

### ISSUE THREAD

**Issue by Limetiime** [dteviot/WebToEpub#963] opened 2023-04-14 21:46 UTC
**Describe the bug**
Only the first and last page of the chapter list is found and added to the list. So when the novel has more than 200 chapters the middle part is excluded.

**To Reproduce**
1. Go to 'https://www.webnovelpub.com/'
2. Go to a novel with more than 200 chapters, 
3. Use addon

**Screenshots**
<img width="700" alt="Screenshot 2023-04-14 at 23 36 57" src="https://user-images.githubusercontent.com/42090185/232159599-e8c257ca-a081-4538-97e0-56911bb5a3df.png">
<img width="716" alt="Screenshot 2023-04-14 at 23 37 06" src="https://user-images.githubusercontent.com/42090185/232159634-7664efb2-467a-4e31-a69d-e0954c874473.png">

**Comment by dteviot** [comment] 2023-04-15 00:39
@Limetiime 

Duplicate of https://github.com/dteviot/WebToEpub/issues/949

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Currently I have RL issues, so no time. Might be a few weeks before I can get around to updating version in Goggle/Firefox stores

**Comment by dteviot** [comment] 2023-05-28 00:15
@Limetiime 

Updated version (0.0.0.154) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.

**Closed by dteviot** 2023-05-28 00:15 UTC
Labels: Status: Completed
