### ISSUE TITLE
Please add https://www.wuxiap.com/

### ISSUE THREAD

**Issue by KBungei** [dteviot/WebToEpub#1056] opened 2023-08-23 13:48 UTC
Hi if it's not too much a bother can you add a parser for https://www.wuxiap.com/
It was formerly  https://readwn.com/ and WebToEpub worked just fine before, but they changed something and the domain so the parser broke
Please fix that, thanks

**Comment by dteviot** [comment] 2023-08-23 19:51
@KBungei 

Duplicate of https://github.com/dteviot/WebToEpub/issues/1004

Release version in Chrome and Firefox stores has not been updated yet.  
However, the in Development version supports this.

Development versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by KBungei** [comment] 2023-08-26 14:55
It works, thank you

**Comment by dteviot** [comment] 2023-09-11 08:16
@KBungei 

Updated version (0.0.0.155) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.

**Comment by Adrianjack** [comment] 2023-11-23 10:58
It's now wuxiabee or smtg!

**Comment by dteviot** [comment] 2023-11-28 22:54
@Adrianjack @KBungei 

Kiradien provided an update for Wuxiabee  (https://github.com/dteviot/WebToEpub/issues/1121)

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers.

**Closed** 2023-11-28 22:55 UTC
Labels: Status: Duplicate
