### ISSUE TITLE
Add Wuxiaworld support. 

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#5] opened 2016-06-20 10:30 UTC
-If it's possible- I'd like you to add Wuxiaworld support, since there are some nice novels there.
The website has project pages like "www.wuxiaworld.com/wmw-index/", it should be possible to work with.
Thanks anyway.

**Comment by belldandu** [comment] 2016-06-20 10:42
Since i'm not familiar with that site it will take some time to add support for it. If @dteviot beats me to it then so be it. After all i'm going to be keeping the other issues top priority for now.

**Comment by typhoon71** [comment] 2016-06-20 10:55
Np, I can wait.

**Comment by dteviot** [comment] 2016-06-21 01:02
@typhoon71 Unfortunately, not that easy to do.  Each book seems to have a different layout for it's index.  Maybe I'm looking in the wrong place?
That said, I wrote an article on how to build and add parsers to the engine.  http://www.codeproject.com/Articles/1060680/Web-to-EPUB-Extension-for-Chrome
Please read it and give it a try.

**Comment by typhoon71** [comment] 2016-06-21 06:00
mmm, it seems you are right, the index page is not standardized.
I just happened to be interested in that one I posted the link of, and I supposed it was the standard.
I'll have a go at that article, maybe I can do something, maybe not. (I'm not a coder :P)

**Comment by dteviot** [comment] 2016-06-21 07:56
If you get stuck or have questions, you can always drop me a line.

**Comment by typhoon71** [comment] 2016-06-21 08:37
OK, thanks.

**Comment by dteviot** [comment] 2016-08-06 06:10
@typhoon71

Basic parser for Wuxiaworld has been added to ZiursMusings branch.
Feel free to take it for a test drive.

**Comment by typhoon71** [comment] 2016-08-06 07:48
Testing WMW (last chrome, and vivaldi too)

1. Unrelated link at the start "http://www.qidian.com/Book/3456256.aspx"

2. double (random) chapter links; the duplicated is correct but in the wrong place, and empty description. It's random, if you reload the page the dupes change.

![err3](https://cloud.githubusercontent.com/assets/1866248/17455537/a80a7b7e-5bba-11e6-9b85-8ba2b8624e37.png)

3. A black line appears at the start of the chapters. There's one at the end of the first too.

![err4](https://cloud.githubusercontent.com/assets/1866248/17455540/b0c6f13e-5bba-11e6-82f2-7e4f7cd75cc0.png)

4. I noticed I can't rename titles, or more line what I type in the box doesn't go in the epub. I never used it before so I don't know how it's supposed to work.

**Comment by dteviot** [comment] 2016-08-07 02:06
@typhoon71

See latest commits to Ziru's Musings branch.
- Now only offers links for “www.wuxiaworld.com” as possible chapters.
- “blank” links are ignored.  (The blank links appear to be garbage in the list of chapters.)
- I've done what I can to remove the “black lines”.  Unfortunately, due to the (mis) formatting of some chapters (see 7 killers) I'm not always able to determine which &lt;hr /&gt; tags relate to the Next/Previous chapter links.
- Renaming chapter titles is working for me with Chrome version 51.0.2704.103  (it updated last night).

Side note, Firefox version 48 was released a couple of days ago. So I can stop trying to figure out how to work around some of its quirks.

**Comment by typhoon71** [comment] 2016-08-07 09:04
Will test new build.

Just a note about renaming the chapters: I actually misunderstood. 
I was assuming the chapter name would be modified in the chapter text itself, while it's the TOC name that gets renamed (the xhtml name actually).
I never used that before (the TOC on calibre) so I got it wrong. 
Sorry for the trouble.

**Comment by typhoon71** [comment] 2016-08-07 09:21
Faster than expected.
1 Blank links fixed, thanks.
2 Black lines are removed.
3 7 killers has somthing strange indeed; it loses some formatting too. 

About FFOX 48 being released, what did you mean about it? I didn't get what yo uwere saying.

**Comment by dteviot** [comment] 2016-08-07 19:37
@typhoon71 
>About FFOX 48 being released, what did you mean about it? I didn't get what you were saying.

FFOX 47 had big problems with tab mode.  The major one being it would not open the tab window when passing parameters to it.  FFOX 48 will allow parameters, but it's still a problem to get it to open the Tab window when it's not responding to a user clicking a button.  (Still on my to-to list to fix.)

**Comment by dteviot** [comment] 2016-08-10 19:50
@typhoon71 
> 3 7 killers has somthing strange indeed; it loses some formatting too.

Well, this is embarrassing.  Looks like I made an error with the "remove next/previous" chapter code.  Fix has just been checked in.  So is now removing them from 7 killers.  I'll also add, those chapters appear to have bad formatting to begin with.  e.g. The footnotes don't have working links.  What else did you notice?

**Comment by typhoon71** [comment] 2016-08-11 19:30
I checked 7 killers just because you told me "see 7 killers", so I reported what I noticed. XD
New build seems OK. No problems on WMW too, aside from an empty white page.

**Comment by dteviot** [comment] 2016-08-12 02:14
@typhoon71 
>No problems on WMW too, aside from an empty white page.

Can you tell me where this this appears?

**Comment by typhoon71** [comment] 2016-08-12 05:52
It's at the end of WMW ch 01, just after the notes.

**Comment by dteviot** [comment] 2016-08-14 05:29
@typhoon71 
> It's at the end of WMW ch 01, just after the notes.

Odd.  It might be some tailing white space at the end of the chapter inside the list.  But I don't see anything obvious.  Can you make it go away by editing the chapter in Calibre?
That should confirm the cause.

**Comment by typhoon71** [comment] 2016-08-15 08:38
I don't see anything "extra" that could be the cause. In sigil I  don't see anything that catches my attention, but I'm not an expert.
The only thing i noticed is that on ch1 there's a footnote while on ch2 there isn't any.

**Comment by dteviot** [comment] 2016-08-20 04:52
@typhoon71 

I'm reasonably sure the "blank page at end of chapter" is a pagination artefact.
If you change the size of the page, the blank page disappears.
The footnotes are in an ordered list and its &lt;ol&gt; and &lt;/ol&gt; tags both inject a new line.
What is happening is the page length combined with the the epub viewer's "page length" makes the &lt;li&gt; occur at the bottom of the page of the last chapter.
However, the closing &lt;/ol&gt; tag creates a new line, which appears at top of next "blank" page.
The rest of page is blank because it's the end of the chapter.

**Closed by dteviot** 2016-08-20 04:52 UTC
Labels: enhancement, low priority

**Comment by typhoon71** [comment] 2016-08-20 06:28
Yeah, I did notice that changing the size of the page (or the font), the blank page disappears.
Is that something to report to calibre? Is it actually considered a bug?

**Comment by dteviot** [comment] 2016-08-21 02:47
@typhoon71

On the basis that it's not doing what a user would expect, I'd say that yes, it is a bug,
I'm not sure the developer would regard it as worth the effort to fix.  But I suppose there's no harm in you creating a bug for it, if you want.

**Comment by Lytzchu** [comment] 2018-03-09 09:53
wuxiaworld link does not work for WebToEpub..

**Comment by dteviot** [comment] 2018-03-09 09:58
@Lytzchu
> wuxiaworld link does not work for WebToEpub..

Fixed.  See: https://github.com/dteviot/WebToEpub/issues/157
