### ISSUE TITLE
getting a failed with network error 422

### ISSUE THREAD

**Issue by God-Jiexi** [dteviot/WebToEpub#301] opened 2019-11-04 17:35 UTC
Hello, i tried using the extension for a novel on babelnovel and i keep getting this error when i try to pack the epub. it happens with every novel i tried so far.

error: "Error: Fetch of URL 'https://babelnovel.com/api//books/supreme-evil-sovereign/chapters/C1' failed with network error 422.
    at FetchErrorHandler.onResponseError (chrome-extension://ldfllmigepgfeloiiihhfgpggicimjfj/js/HttpClient.js:28:25)
    at Function.checkResponseAndGetData (chrome-extension://ldfllmigepgfeloiiihhfgpggicimjfj/js/HttpClient.js:163:45)
    at chrome-extension://ldfllmigepgfeloiiihhfgpggicimjfj/js/HttpClient.js:157:31
    at async Promise.all (index 0)"
As this is my first time trying the extension, i dont know if im doing something wrong.

**Comment by dteviot** [comment] 2019-11-04 18:06
@God-Jiexi 
Duplicate of https://github.com/dteviot/WebToEpub/issues/300,  I'm currently working on a fix

**Comment by dteviot** [comment] 2019-11-04 19:01
@God-Jiexi
New version (0.0.0.92) has been uploaded to Chrome and Mozilla stores. Your copy should update automatically within 24 hours.

Now closing this as it's a duplicate.

**Closed by dteviot** 2019-11-04 19:01 UTC
